%%% @author Mykola Konyk <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% @license MS-RL
%%% This file is autogenerated from util/hapi_record.hrl.template
%%% This file corresponds to HAPI_VolumeTileInfo structure from HAPI_Common.h

-record(hapi_volumetileinfo,
{
    min_x,
    min_y,
    min_z,
    is_valid
}).
