%%% @author Mykola Konyk <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% @license MS-RL
%%% This file is autogenerated from util/hapi_record.hrl.template
%%% This file corresponds to HAPI_TransformEuler structure from HAPI_Common.h

-record(hapi_transformeuler,
{
    position,
    rotation_euler,
    scale,
    rotation_order,
    rst_order
}).
