%%% @author Mykola Konyk <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% @license MS-RL
%%% This file is autogenerated from util/hapi_record.hrl.template
%%% This file corresponds to HAPI_CookOptions structure from HAPI_Common.h

-record(hapi_cookoptions,
{
    split_geos_by_group,
    max_vertices_per_primitive,
    refine_curve_to_linear,
    curve_refine_lod,
    clear_errors_and_warnings,
    cook_templated_geos
}).
