%%% @author Mykola Konyk <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% @license MS-RL
%%% This file is autogenerated from util/hapi_record.hrl.template
%%% This file corresponds to HAPI_HandleBindingInfo structure from HAPI_Common.h

-record(hapi_handlebindinginfo,
{
    handle_parm_name_sh,
    asset_parm_name_sh,
    asset_parm_id
}).
