%%% @author Mykola Konyk <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% @license MS-RL
%%% This file is autogenerated from util/hapi_record.hrl.template
%%% This file corresponds to HAPI_Transform structure from HAPI_Common.h

-record(hapi_transform,
{
    position,
    rotation_quaternion,
    scale,
    rst_order
}).
