%%% @author Mykola Konyk <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% @license MS-RL
%%% This file is autogenerated from util/hapi_record.hrl.template
%%% This file corresponds to HAPI_Keyframe structure from HAPI_Common.h

-record(hapi_keyframe,
{
    time,
    value,
    in_tangent,
    out_tangent
}).
