%%% @author Mykola Konyk <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% @license MS-RL
%%% This file is autogenerated from util/hapi_record.hrl.template
%%% This file corresponds to HAPI_HandleInfo structure from HAPI_Common.h

-record(hapi_handle_info,
{
    name_sh,
    type_name_sh,
    bindings_count
}).
