/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_VolumeTileInfo struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include "../hapi_enums_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_volume_tile_info(ErlNifEnv* env, const HAPI_VolumeTileInfo* hapi_struct)
{
    return enif_make_tuple(env, 5,
        hapi_make_atom(env, "hapi_volume_tile_info"),
        hapi_make_int(env, hapi_struct->minX),
        hapi_make_int(env, hapi_struct->minY),
        hapi_make_int(env, hapi_struct->minZ),
        hapi_make_bool(env, (bool) hapi_struct->isValid));
}


bool
hapi_get_hapi_volume_tile_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_VolumeTileInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    int32_t record_min_x = 0;
    int32_t record_min_y = 0;
    int32_t record_min_z = 0;
    bool record_is_valid = false;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 5) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_volume_tile_info", &atom_name_match) ||
        !atom_name_match ||
        !hapi_get_int(env, tuple_record[1], &record_min_x) ||
        !hapi_get_int(env, tuple_record[2], &record_min_y) ||
        !hapi_get_int(env, tuple_record[3], &record_min_z) ||
        !hapi_get_bool(env, tuple_record[4], &record_is_valid))
    {
        return false;
    }

    hapi_struct->minX = record_min_x;
    hapi_struct->minY = record_min_y;
    hapi_struct->minZ = record_min_z;
    hapi_struct->isValid = (HAPI_Bool) record_is_valid;

    return true;
}


ERL_NIF_TERM
hapi_make_hapi_volume_tile_info_list(ErlNifEnv* env, const HAPI_VolumeTileInfo* hapi_structs, int32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_VolumeTileInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_volume_tile_info(env, hapi_struct), list);
    }

    return list;
}


bool
hapi_get_hapi_volume_tile_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_VolumeTileInfo* hapi_structs, int32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_VolumeTileInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_volume_tile_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}
