/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_MaterialInfo struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include "../hapi_enums_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_material_info(ErlNifEnv* env, const HAPI_MaterialInfo* hapi_struct)
{
    return enif_make_tuple(env, 6,
        hapi_make_atom(env, "hapi_material_info"),
        enif_make_int(env, (int32_t) hapi_struct->id),
        enif_make_int(env, (int32_t) hapi_struct->assetId),
        enif_make_int(env, (int32_t) hapi_struct->nodeId),
        hapi_make_atom_bool(env, (bool) hapi_struct->exists),
        hapi_make_atom_bool(env, (bool) hapi_struct->hasChanged));
}


bool
hapi_get_hapi_material_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_MaterialInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    int32_t record_id = 0;
    int32_t record_asset_id = 0;
    int32_t record_node_id = 0;
    bool record_exists = false;
    bool record_has_changed = false;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 6) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_material_info", &atom_name_match) ||
        !atom_name_match ||
        !enif_get_int(env, tuple_record[1], &record_id) ||
        !enif_get_int(env, tuple_record[2], &record_asset_id) ||
        !enif_get_int(env, tuple_record[3], &record_node_id) ||
        !hapi_get_atom_bool(env, tuple_record[4], &record_exists) ||
        !hapi_get_atom_bool(env, tuple_record[5], &record_has_changed))
    {
        return false;
    }

    hapi_struct->id = (HAPI_MaterialId) record_id;
    hapi_struct->assetId = (HAPI_AssetId) record_asset_id;
    hapi_struct->nodeId = (HAPI_NodeId) record_node_id;
    hapi_struct->exists = (HAPI_Bool) record_exists;
    hapi_struct->hasChanged = (HAPI_Bool) record_has_changed;

    return true;
}


ERL_NIF_TERM
hapi_make_hapi_material_info_list(ErlNifEnv* env, const HAPI_MaterialInfo* hapi_structs, int32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_MaterialInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_material_info(env, hapi_struct), list);
    }

    return list;
}


bool
hapi_get_hapi_material_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_MaterialInfo* hapi_structs, int32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_MaterialInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_material_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}
