/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_ParmChoiceInfo struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include "../hapi_enums_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_parmchoiceinfo(ErlNifEnv* env, const HAPI_ParmChoiceInfo* hapi_struct)
{
    return enif_make_tuple(env, 4,
        hapi_make_atom(env, "hapi_parmchoiceinfo"),
        enif_make_int(env, (int32_t) hapi_struct->parentParmId),
        enif_make_int(env, (int32_t) hapi_struct->labelSH),
        enif_make_int(env, (int32_t) hapi_struct->valueSH));
}


bool
hapi_get_hapi_parmchoiceinfo(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ParmChoiceInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    int32_t record_parent_parm_id = 0;
    int32_t record_label_sh = 0;
    int32_t record_value_sh = 0;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 4) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_parmchoiceinfo", &atom_name_match) ||
        !atom_name_match ||
        !enif_get_int(env, tuple_record[1], &record_parent_parm_id) ||
        !enif_get_int(env, tuple_record[2], &record_label_sh) ||
        !enif_get_int(env, tuple_record[3], &record_value_sh))
    {
        return false;
    }

    hapi_struct->parentParmId = (HAPI_ParmId) record_parent_parm_id;
    hapi_struct->labelSH = (HAPI_StringHandle) record_label_sh;
    hapi_struct->valueSH = (HAPI_StringHandle) record_value_sh;

    return true;
}
