/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_AttributeInfo struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_attributeinfo(ErlNifEnv* env, const HAPI_AttributeInfo* hapi_struct)
{
    return enif_make_tuple(env, 7,
        hapi_make_atom(env, "hapi_attributeinfo"),
        hapi_make_atom_bool(env, (bool) hapi_struct->exists),
        enif_make_int(env, (int32_t) hapi_struct->owner),
        enif_make_int(env, (int32_t) hapi_struct->storage),
        enif_make_int(env, (int32_t) hapi_struct->originalOwner),
        enif_make_int(env, hapi_struct->count),
        enif_make_int(env, hapi_struct->tupleSize));
}


bool
hapi_get_hapi_attributeinfo(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_AttributeInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    bool record_exists = false;
    int32_t record_owner = 0;
    int32_t record_storage = 0;
    int32_t record_original_owner = 0;
    int32_t record_count = 0;
    int32_t record_tuple_size = 0;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 7) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_attributeinfo", &atom_name_match) ||
        !atom_name_match ||
        !hapi_get_atom_bool(env, tuple_record[1], &record_exists) ||
        !enif_get_int(env, tuple_record[2], &record_owner) ||
        !enif_get_int(env, tuple_record[3], &record_storage) ||
        !enif_get_int(env, tuple_record[4], &record_original_owner) ||
        !enif_get_int(env, tuple_record[5], &record_count) ||
        !enif_get_int(env, tuple_record[6], &record_tuple_size))
    {
        return false;
    }

    hapi_struct->exists = (HAPI_Bool) record_exists;
    hapi_struct->owner = (HAPI_AttributeOwner) record_owner;
    hapi_struct->storage = (HAPI_StorageType) record_storage;
    hapi_struct->originalOwner = (HAPI_AttributeOwner) record_original_owner;
    hapi_struct->count = record_count;
    hapi_struct->tupleSize = record_tuple_size;

    return true;
}
