/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_GlobalNodes struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include "../hapi_enums_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_global_nodes(ErlNifEnv* env, const HAPI_GlobalNodes* hapi_struct)
{
    return enif_make_tuple(env, 4,
        hapi_make_atom(env, "hapi_global_nodes"),
        enif_make_int(env, (int32_t) hapi_struct->defaultCamera),
        enif_make_int(env, (int32_t) hapi_struct->defaultLight),
        enif_make_int(env, (int32_t) hapi_struct->mantraRenderer));
}


bool
hapi_get_hapi_global_nodes(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_GlobalNodes* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    int32_t record_default_camera = 0;
    int32_t record_default_light = 0;
    int32_t record_mantra_renderer = 0;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 4) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_global_nodes", &atom_name_match) ||
        !atom_name_match ||
        !enif_get_int(env, tuple_record[1], &record_default_camera) ||
        !enif_get_int(env, tuple_record[2], &record_default_light) ||
        !enif_get_int(env, tuple_record[3], &record_mantra_renderer))
    {
        return false;
    }

    hapi_struct->defaultCamera = (HAPI_NodeId) record_default_camera;
    hapi_struct->defaultLight = (HAPI_NodeId) record_default_light;
    hapi_struct->mantraRenderer = (HAPI_NodeId) record_mantra_renderer;

    return true;
}
