/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_ObjectInfo struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include "../hapi_enums_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_objectinfo(ErlNifEnv* env, const HAPI_ObjectInfo* hapi_struct)
{
    return enif_make_tuple(env, 11,
        hapi_make_atom(env, "hapi_objectinfo"),
        enif_make_int(env, (int32_t) hapi_struct->id),
        enif_make_int(env, (int32_t) hapi_struct->nameSH),
        enif_make_int(env, (int32_t) hapi_struct->objectInstancePathSH),
        hapi_make_atom_bool(env, (bool) hapi_struct->hasTransformChanged),
        hapi_make_atom_bool(env, (bool) hapi_struct->haveGeosChanged),
        hapi_make_atom_bool(env, (bool) hapi_struct->isVisible),
        hapi_make_atom_bool(env, (bool) hapi_struct->isInstancer),
        enif_make_int(env, hapi_struct->geoCount),
        enif_make_int(env, (int32_t) hapi_struct->nodeId),
        enif_make_int(env, (int32_t) hapi_struct->objectToInstanceId));
}


bool
hapi_get_hapi_objectinfo(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ObjectInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    int32_t record_id = 0;
    int32_t record_name_sh = 0;
    int32_t record_object_instance_path_sh = 0;
    bool record_has_transform_changed = false;
    bool record_have_geos_changed = false;
    bool record_is_visible = false;
    bool record_is_instancer = false;
    int32_t record_geo_count = 0;
    int32_t record_node_id = 0;
    int32_t record_object_to_instance_id = 0;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 11) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_objectinfo", &atom_name_match) ||
        !atom_name_match ||
        !enif_get_int(env, tuple_record[1], &record_id) ||
        !enif_get_int(env, tuple_record[2], &record_name_sh) ||
        !enif_get_int(env, tuple_record[3], &record_object_instance_path_sh) ||
        !hapi_get_atom_bool(env, tuple_record[4], &record_has_transform_changed) ||
        !hapi_get_atom_bool(env, tuple_record[5], &record_have_geos_changed) ||
        !hapi_get_atom_bool(env, tuple_record[6], &record_is_visible) ||
        !hapi_get_atom_bool(env, tuple_record[7], &record_is_instancer) ||
        !enif_get_int(env, tuple_record[8], &record_geo_count) ||
        !enif_get_int(env, tuple_record[9], &record_node_id) ||
        !enif_get_int(env, tuple_record[10], &record_object_to_instance_id))
    {
        return false;
    }

    hapi_struct->id = (HAPI_ObjectId) record_id;
    hapi_struct->nameSH = (HAPI_StringHandle) record_name_sh;
    hapi_struct->objectInstancePathSH = (HAPI_StringHandle) record_object_instance_path_sh;
    hapi_struct->hasTransformChanged = (HAPI_Bool) record_has_transform_changed;
    hapi_struct->haveGeosChanged = (HAPI_Bool) record_have_geos_changed;
    hapi_struct->isVisible = (HAPI_Bool) record_is_visible;
    hapi_struct->isInstancer = (HAPI_Bool) record_is_instancer;
    hapi_struct->geoCount = record_geo_count;
    hapi_struct->nodeId = (HAPI_NodeId) record_node_id;
    hapi_struct->objectToInstanceId = (HAPI_ObjectId) record_object_to_instance_id;

    return true;
}
