/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_PartInfo struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include "../hapi_enums_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_partinfo(ErlNifEnv* env, const HAPI_PartInfo* hapi_struct)
{
    return enif_make_tuple(env, 12,
        hapi_make_atom(env, "hapi_partinfo"),
        enif_make_int(env, (int32_t) hapi_struct->id),
        enif_make_int(env, (int32_t) hapi_struct->nameSH),
        enif_make_int(env, hapi_struct->faceCount),
        enif_make_int(env, hapi_struct->vertexCount),
        enif_make_int(env, hapi_struct->pointCount),
        enif_make_int(env, hapi_struct->pointAttributeCount),
        enif_make_int(env, hapi_struct->faceAttributeCount),
        enif_make_int(env, hapi_struct->vertexAttributeCount),
        enif_make_int(env, hapi_struct->detailAttributeCount),
        hapi_make_atom_bool(env, (bool) hapi_struct->hasVolume),
        hapi_make_atom_bool(env, (bool) hapi_struct->isCurve));
}


bool
hapi_get_hapi_partinfo(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_PartInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    int32_t record_id = 0;
    int32_t record_name_sh = 0;
    int32_t record_face_count = 0;
    int32_t record_vertex_count = 0;
    int32_t record_point_count = 0;
    int32_t record_point_attribute_count = 0;
    int32_t record_face_attribute_count = 0;
    int32_t record_vertex_attribute_count = 0;
    int32_t record_detail_attribute_count = 0;
    bool record_has_volume = false;
    bool record_is_curve = false;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 12) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_partinfo", &atom_name_match) ||
        !atom_name_match ||
        !enif_get_int(env, tuple_record[1], &record_id) ||
        !enif_get_int(env, tuple_record[2], &record_name_sh) ||
        !enif_get_int(env, tuple_record[3], &record_face_count) ||
        !enif_get_int(env, tuple_record[4], &record_vertex_count) ||
        !enif_get_int(env, tuple_record[5], &record_point_count) ||
        !enif_get_int(env, tuple_record[6], &record_point_attribute_count) ||
        !enif_get_int(env, tuple_record[7], &record_face_attribute_count) ||
        !enif_get_int(env, tuple_record[8], &record_vertex_attribute_count) ||
        !enif_get_int(env, tuple_record[9], &record_detail_attribute_count) ||
        !hapi_get_atom_bool(env, tuple_record[10], &record_has_volume) ||
        !hapi_get_atom_bool(env, tuple_record[11], &record_is_curve))
    {
        return false;
    }

    hapi_struct->id = (HAPI_PartId) record_id;
    hapi_struct->nameSH = (HAPI_StringHandle) record_name_sh;
    hapi_struct->faceCount = record_face_count;
    hapi_struct->vertexCount = record_vertex_count;
    hapi_struct->pointCount = record_point_count;
    hapi_struct->pointAttributeCount = record_point_attribute_count;
    hapi_struct->faceAttributeCount = record_face_attribute_count;
    hapi_struct->vertexAttributeCount = record_vertex_attribute_count;
    hapi_struct->detailAttributeCount = record_detail_attribute_count;
    hapi_struct->hasVolume = (HAPI_Bool) record_has_volume;
    hapi_struct->isCurve = (HAPI_Bool) record_is_curve;

    return true;
}
