/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_Keyframe struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include "../hapi_enums_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_keyframe(ErlNifEnv* env, const HAPI_Keyframe* hapi_struct)
{
    return enif_make_tuple(env, 5,
        hapi_make_atom(env, "hapi_keyframe"),
        hapi_make_float(env, (double) hapi_struct->time),
        hapi_make_float(env, (double) hapi_struct->value),
        hapi_make_float(env, (double) hapi_struct->inTangent),
        hapi_make_float(env, (double) hapi_struct->outTangent));
}


bool
hapi_get_hapi_keyframe(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_Keyframe* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    float record_time = 0.0f;
    float record_value = 0.0f;
    float record_in_tangent = 0.0f;
    float record_out_tangent = 0.0f;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 5) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_keyframe", &atom_name_match) ||
        !atom_name_match ||
        !hapi_get_float(env, tuple_record[1], &record_time) ||
        !hapi_get_float(env, tuple_record[2], &record_value) ||
        !hapi_get_float(env, tuple_record[3], &record_in_tangent) ||
        !hapi_get_float(env, tuple_record[4], &record_out_tangent))
    {
        return false;
    }

    hapi_struct->time = (float) record_time;
    hapi_struct->value = (float) record_value;
    hapi_struct->inTangent = (float) record_in_tangent;
    hapi_struct->outTangent = (float) record_out_tangent;

    return true;
}


ERL_NIF_TERM
hapi_make_hapi_keyframe_list(ErlNifEnv* env, const HAPI_Keyframe* hapi_structs, int32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_Keyframe* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_keyframe(env, hapi_struct), list);
    }

    return list;
}


bool
hapi_get_hapi_keyframe_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_Keyframe* hapi_structs, int32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_Keyframe* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_keyframe(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}
