/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_VolumeTileInfo struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include "../hapi_enums_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_volumetileinfo(ErlNifEnv* env, const HAPI_VolumeTileInfo* hapi_struct)
{
    return enif_make_tuple(env, 5,
        hapi_make_atom(env, "hapi_volumetileinfo"),
        enif_make_int(env, hapi_struct->minX),
        enif_make_int(env, hapi_struct->minY),
        enif_make_int(env, hapi_struct->minZ),
        hapi_make_atom_bool(env, (bool) hapi_struct->isValid));
}


bool
hapi_get_hapi_volumetileinfo(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_VolumeTileInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    int32_t record_min_x = 0;
    int32_t record_min_y = 0;
    int32_t record_min_z = 0;
    bool record_is_valid = false;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 5) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_volumetileinfo", &atom_name_match) ||
        !atom_name_match ||
        !enif_get_int(env, tuple_record[1], &record_min_x) ||
        !enif_get_int(env, tuple_record[2], &record_min_y) ||
        !enif_get_int(env, tuple_record[3], &record_min_z) ||
        !hapi_get_atom_bool(env, tuple_record[4], &record_is_valid))
    {
        return false;
    }

    hapi_struct->minX = record_min_x;
    hapi_struct->minY = record_min_y;
    hapi_struct->minZ = record_min_z;
    hapi_struct->isValid = (HAPI_Bool) record_is_valid;

    return true;
}
