/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_NodeInfo struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include "../hapi_enums_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_node_info(ErlNifEnv* env, const HAPI_NodeInfo* hapi_struct)
{
    return enif_make_tuple(env, 12,
        hapi_make_atom(env, "hapi_node_info"),
        hapi_make_int(env, (int32_t) hapi_struct->id),
        hapi_make_int(env, (int32_t) hapi_struct->assetId),
        hapi_make_int(env, (int32_t) hapi_struct->nameSH),
        hapi_make_int(env, hapi_struct->totalCookCount),
        hapi_make_int(env, hapi_struct->uniqueHoudiniNodeId),
        hapi_make_int(env, (int32_t) hapi_struct->internalNodePathSH),
        hapi_make_int(env, hapi_struct->parmCount),
        hapi_make_int(env, hapi_struct->parmIntValueCount),
        hapi_make_int(env, hapi_struct->parmFloatValueCount),
        hapi_make_int(env, hapi_struct->parmStringValueCount),
        hapi_make_int(env, hapi_struct->parmChoiceCount));
}


bool
hapi_get_hapi_node_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_NodeInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    int32_t record_id = 0;
    int32_t record_asset_id = 0;
    int32_t record_name_sh = 0;
    int32_t record_total_cook_count = 0;
    int32_t record_unique_houdini_node_id = 0;
    int32_t record_internal_node_path_sh = 0;
    int32_t record_parm_count = 0;
    int32_t record_parm_int_value_count = 0;
    int32_t record_parm_float_value_count = 0;
    int32_t record_parm_string_value_count = 0;
    int32_t record_parm_choice_count = 0;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 12) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_node_info", &atom_name_match) ||
        !atom_name_match ||
        !hapi_get_int(env, tuple_record[1], &record_id) ||
        !hapi_get_int(env, tuple_record[2], &record_asset_id) ||
        !hapi_get_int(env, tuple_record[3], &record_name_sh) ||
        !hapi_get_int(env, tuple_record[4], &record_total_cook_count) ||
        !hapi_get_int(env, tuple_record[5], &record_unique_houdini_node_id) ||
        !hapi_get_int(env, tuple_record[6], &record_internal_node_path_sh) ||
        !hapi_get_int(env, tuple_record[7], &record_parm_count) ||
        !hapi_get_int(env, tuple_record[8], &record_parm_int_value_count) ||
        !hapi_get_int(env, tuple_record[9], &record_parm_float_value_count) ||
        !hapi_get_int(env, tuple_record[10], &record_parm_string_value_count) ||
        !hapi_get_int(env, tuple_record[11], &record_parm_choice_count))
    {
        return false;
    }

    hapi_struct->id = (HAPI_NodeId) record_id;
    hapi_struct->assetId = (HAPI_AssetId) record_asset_id;
    hapi_struct->nameSH = (HAPI_StringHandle) record_name_sh;
    hapi_struct->totalCookCount = record_total_cook_count;
    hapi_struct->uniqueHoudiniNodeId = record_unique_houdini_node_id;
    hapi_struct->internalNodePathSH = (HAPI_StringHandle) record_internal_node_path_sh;
    hapi_struct->parmCount = record_parm_count;
    hapi_struct->parmIntValueCount = record_parm_int_value_count;
    hapi_struct->parmFloatValueCount = record_parm_float_value_count;
    hapi_struct->parmStringValueCount = record_parm_string_value_count;
    hapi_struct->parmChoiceCount = record_parm_choice_count;

    return true;
}


ERL_NIF_TERM
hapi_make_hapi_node_info_list(ErlNifEnv* env, const HAPI_NodeInfo* hapi_structs, int32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_NodeInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_node_info(env, hapi_struct), list);
    }

    return list;
}


bool
hapi_get_hapi_node_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_NodeInfo* hapi_structs, int32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_NodeInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_node_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}
