/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_CookOptions struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include "../hapi_enums_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_cook_options(ErlNifEnv* env, const HAPI_CookOptions* hapi_struct)
{
    return enif_make_tuple(env, 7,
        hapi_make_atom(env, "hapi_cook_options"),
        hapi_make_bool(env, (bool) hapi_struct->splitGeosByGroup),
        hapi_make_int(env, hapi_struct->maxVerticesPerPrimitive),
        hapi_make_bool(env, (bool) hapi_struct->refineCurveToLinear),
        hapi_make_float(env, (double) hapi_struct->curveRefineLOD),
        hapi_make_bool(env, (bool) hapi_struct->clearErrorsAndWarnings),
        hapi_make_bool(env, (bool) hapi_struct->cookTemplatedGeos));
}


bool
hapi_get_hapi_cook_options(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_CookOptions* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    bool record_split_geos_by_group = false;
    int32_t record_max_vertices_per_primitive = 0;
    bool record_refine_curve_to_linear = false;
    float record_curve_refine_lod = 0.0f;
    bool record_clear_errors_and_warnings = false;
    bool record_cook_templated_geos = false;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 7) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_cook_options", &atom_name_match) ||
        !atom_name_match ||
        !hapi_get_bool(env, tuple_record[1], &record_split_geos_by_group) ||
        !hapi_get_int(env, tuple_record[2], &record_max_vertices_per_primitive) ||
        !hapi_get_bool(env, tuple_record[3], &record_refine_curve_to_linear) ||
        !hapi_get_float(env, tuple_record[4], &record_curve_refine_lod) ||
        !hapi_get_bool(env, tuple_record[5], &record_clear_errors_and_warnings) ||
        !hapi_get_bool(env, tuple_record[6], &record_cook_templated_geos))
    {
        return false;
    }

    hapi_struct->splitGeosByGroup = (HAPI_Bool) record_split_geos_by_group;
    hapi_struct->maxVerticesPerPrimitive = record_max_vertices_per_primitive;
    hapi_struct->refineCurveToLinear = (HAPI_Bool) record_refine_curve_to_linear;
    hapi_struct->curveRefineLOD = (float) record_curve_refine_lod;
    hapi_struct->clearErrorsAndWarnings = (HAPI_Bool) record_clear_errors_and_warnings;
    hapi_struct->cookTemplatedGeos = (HAPI_Bool) record_cook_templated_geos;

    return true;
}


ERL_NIF_TERM
hapi_make_hapi_cook_options_list(ErlNifEnv* env, const HAPI_CookOptions* hapi_structs, int32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_CookOptions* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_cook_options(env, hapi_struct), list);
    }

    return list;
}


bool
hapi_get_hapi_cook_options_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_CookOptions* hapi_structs, int32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_CookOptions* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_cook_options(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}
