/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_HandleBindingInfo struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include "../hapi_enums_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_handle_binding_info(ErlNifEnv* env, const HAPI_HandleBindingInfo* hapi_struct)
{
    return enif_make_tuple(env, 4,
        hapi_make_atom(env, "hapi_handle_binding_info"),
        enif_make_int(env, (int32_t) hapi_struct->handleParmNameSH),
        enif_make_int(env, (int32_t) hapi_struct->assetParmNameSH),
        enif_make_int(env, (int32_t) hapi_struct->assetParmId));
}


bool
hapi_get_hapi_handle_binding_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_HandleBindingInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    int32_t record_handle_parm_name_sh = 0;
    int32_t record_asset_parm_name_sh = 0;
    int32_t record_asset_parm_id = 0;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 4) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_handle_binding_info", &atom_name_match) ||
        !atom_name_match ||
        !enif_get_int(env, tuple_record[1], &record_handle_parm_name_sh) ||
        !enif_get_int(env, tuple_record[2], &record_asset_parm_name_sh) ||
        !enif_get_int(env, tuple_record[3], &record_asset_parm_id))
    {
        return false;
    }

    hapi_struct->handleParmNameSH = (HAPI_StringHandle) record_handle_parm_name_sh;
    hapi_struct->assetParmNameSH = (HAPI_StringHandle) record_asset_parm_name_sh;
    hapi_struct->assetParmId = (HAPI_ParmId) record_asset_parm_id;

    return true;
}


ERL_NIF_TERM
hapi_make_hapi_handle_binding_info_list(ErlNifEnv* env, const HAPI_HandleBindingInfo* hapi_structs, int32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_HandleBindingInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_handle_binding_info(env, hapi_struct), list);
    }

    return list;
}


bool
hapi_get_hapi_handle_binding_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_HandleBindingInfo* hapi_structs, int32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_HandleBindingInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_handle_binding_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}
