/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_ImageFileFormat struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_imagefileformat(ErlNifEnv* env, const HAPI_ImageFileFormat* hapi_struct)
{
    return enif_make_tuple(env, 4,
        hapi_make_atom(env, "hapi_imagefileformat"),
        enif_make_int(env, (int32_t) hapi_struct->nameSH),
        enif_make_int(env, (int32_t) hapi_struct->descriptionSH),
        enif_make_int(env, (int32_t) hapi_struct->defaultExtensionSH));
}


bool
hapi_get_hapi_imagefileformat(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ImageFileFormat* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    int32_t record_name_sh = 0;
    int32_t record_description_sh = 0;
    int32_t record_default_extension_sh = 0;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 4) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_imagefileformat", &atom_name_match) ||
        !atom_name_match ||
        !enif_get_int(env, tuple_record[1], &record_name_sh) ||
        !enif_get_int(env, tuple_record[2], &record_description_sh) ||
        !enif_get_int(env, tuple_record[3], &record_default_extension_sh))
    {
        return false;
    }

    hapi_struct->nameSH = (HAPI_StringHandle) record_name_sh;
    hapi_struct->descriptionSH = (HAPI_StringHandle) record_description_sh;
    hapi_struct->defaultExtensionSH = (HAPI_StringHandle) record_default_extension_sh;

    return true;
}
