/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_Keyframe struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_keyframe(ErlNifEnv* env, const HAPI_Keyframe* hapi_struct)
{
    return enif_make_tuple(env, 5,
        hapi_make_atom(env, "hapi_keyframe"),
        enif_make_double(env, (double) hapi_struct->time),
        enif_make_double(env, (double) hapi_struct->value),
        enif_make_double(env, (double) hapi_struct->inTangent),
        enif_make_double(env, (double) hapi_struct->outTangent));
}


bool
hapi_get_hapi_keyframe(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_Keyframe* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    double record_time = 0.0;
    double record_value = 0.0;
    double record_in_tangent = 0.0;
    double record_out_tangent = 0.0;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 5) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_keyframe", &atom_name_match) ||
        !atom_name_match ||
        !enif_get_double(env, tuple_record[1], &record_time) ||
        !enif_get_double(env, tuple_record[2], &record_value) ||
        !enif_get_double(env, tuple_record[3], &record_in_tangent) ||
        !enif_get_double(env, tuple_record[4], &record_out_tangent))
    {
        return false;
    }

    hapi_struct->time = (float) record_time;
    hapi_struct->value = (float) record_value;
    hapi_struct->inTangent = (float) record_in_tangent;
    hapi_struct->outTangent = (float) record_out_tangent;

    return true;
}
