/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_CurveInfo struct from HAPI_Common.h

#include "../hapi_private_nif.h"
#include "../hapi_records_nif.h"
#include "../hapi_enums_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_curve_info(ErlNifEnv* env, const HAPI_CurveInfo* hapi_struct)
{
    return enif_make_tuple(env, 9,
        hapi_make_atom(env, "hapi_curve_info"),
        hapi_make_hapi_curve_type(env, hapi_struct->curveType),
        hapi_make_int(env, hapi_struct->curveCount),
        hapi_make_int(env, hapi_struct->vertexCount),
        hapi_make_int(env, hapi_struct->knotCount),
        hapi_make_bool(env, (bool) hapi_struct->isPeriodic),
        hapi_make_bool(env, (bool) hapi_struct->isRational),
        hapi_make_int(env, hapi_struct->order),
        hapi_make_bool(env, (bool) hapi_struct->hasKnots));
}


bool
hapi_get_hapi_curve_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_CurveInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_CurveType record_curve_type;
    int32_t record_curve_count = 0;
    int32_t record_vertex_count = 0;
    int32_t record_knot_count = 0;
    bool record_is_periodic = false;
    bool record_is_rational = false;
    int32_t record_order = 0;
    bool record_has_knots = false;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 9) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_curve_info", &atom_name_match) ||
        !atom_name_match ||
        !hapi_get_hapi_curve_type(env, tuple_record[1], &record_curve_type) ||
        !hapi_get_int(env, tuple_record[2], &record_curve_count) ||
        !hapi_get_int(env, tuple_record[3], &record_vertex_count) ||
        !hapi_get_int(env, tuple_record[4], &record_knot_count) ||
        !hapi_get_bool(env, tuple_record[5], &record_is_periodic) ||
        !hapi_get_bool(env, tuple_record[6], &record_is_rational) ||
        !hapi_get_int(env, tuple_record[7], &record_order) ||
        !hapi_get_bool(env, tuple_record[8], &record_has_knots))
    {
        return false;
    }

    hapi_struct->curveType = record_curve_type;
    hapi_struct->curveCount = record_curve_count;
    hapi_struct->vertexCount = record_vertex_count;
    hapi_struct->knotCount = record_knot_count;
    hapi_struct->isPeriodic = (HAPI_Bool) record_is_periodic;
    hapi_struct->isRational = (HAPI_Bool) record_is_rational;
    hapi_struct->order = record_order;
    hapi_struct->hasKnots = (HAPI_Bool) record_has_knots;

    return true;
}


ERL_NIF_TERM
hapi_make_hapi_curve_info_list(ErlNifEnv* env, const HAPI_CurveInfo* hapi_structs, int32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_CurveInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_curve_info(env, hapi_struct), list);
    }

    return list;
}


bool
hapi_get_hapi_curve_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_CurveInfo* hapi_structs, int32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_CurveInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_curve_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}
