/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_structuers_nif.c.template

#include "hapi_private_nif.h"
#include "hapi_enums_nif.h"
#include "hapi_types_nif.h"
#include "hapi_structures_nif.h"


/* Converting HAPI_CookOptions from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_cook_options(ErlNifEnv* env, const HAPI_CookOptions* hapi_struct)
{
    return enif_make_tuple(env, 7,
        hapi_make_atom(env, "hapi_cook_options"),
        hapi_make_hapi_bool(env, hapi_struct->splitGeosByGroup),
        hapi_make_int(env, hapi_struct->maxVerticesPerPrimitive),
        hapi_make_hapi_bool(env, hapi_struct->refineCurveToLinear),
        hapi_make_float(env, hapi_struct->curveRefineLOD),
        hapi_make_hapi_bool(env, hapi_struct->clearErrorsAndWarnings),
        hapi_make_hapi_bool(env, hapi_struct->cookTemplatedGeos));
}


/* Converting HAPI_CookOptions from erl to c. */
bool
hapi_get_hapi_cook_options(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_CookOptions* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_Bool var_split_geos_by_group;
    int var_max_vertices_per_primitive;
    HAPI_Bool var_refine_curve_to_linear;
    float var_curve_refine_lod;
    HAPI_Bool var_clear_errors_and_warnings;
    HAPI_Bool var_cook_templated_geos;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 7) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_cook_options", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_CookOptions objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_cook_options_list(ErlNifEnv* env, const HAPI_CookOptions* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_CookOptions* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_cook_options(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_CookOptions objects from erl to c. */
bool
hapi_get_hapi_cook_options_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_CookOptions* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_CookOptions* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_cook_options(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_Keyframe from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_keyframe(ErlNifEnv* env, const HAPI_Keyframe* hapi_struct)
{
    return enif_make_tuple(env, 5,
        hapi_make_atom(env, "hapi_keyframe"),
        hapi_make_float(env, hapi_struct->time),
        hapi_make_float(env, hapi_struct->value),
        hapi_make_float(env, hapi_struct->inTangent),
        hapi_make_float(env, hapi_struct->outTangent));
}


/* Converting HAPI_Keyframe from erl to c. */
bool
hapi_get_hapi_keyframe(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_Keyframe* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    float var_time;
    float var_value;
    float var_in_tangent;
    float var_out_tangent;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 5) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_keyframe", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_Keyframe objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_keyframe_list(ErlNifEnv* env, const HAPI_Keyframe* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_Keyframe* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_keyframe(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_Keyframe objects from erl to c. */
bool
hapi_get_hapi_keyframe_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_Keyframe* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_Keyframe* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_keyframe(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_PartInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_part_info(ErlNifEnv* env, const HAPI_PartInfo* hapi_struct)
{
    return enif_make_tuple(env, 12,
        hapi_make_atom(env, "hapi_part_info"),
        hapi_make_hapi_part_id(env, hapi_struct->id),
        hapi_make_hapi_string_handle(env, hapi_struct->nameSH),
        hapi_make_int(env, hapi_struct->faceCount),
        hapi_make_int(env, hapi_struct->vertexCount),
        hapi_make_int(env, hapi_struct->pointCount),
        hapi_make_int(env, hapi_struct->pointAttributeCount),
        hapi_make_int(env, hapi_struct->faceAttributeCount),
        hapi_make_int(env, hapi_struct->vertexAttributeCount),
        hapi_make_int(env, hapi_struct->detailAttributeCount),
        hapi_make_hapi_bool(env, hapi_struct->hasVolume),
        hapi_make_hapi_bool(env, hapi_struct->isCurve));
}


/* Converting HAPI_PartInfo from erl to c. */
bool
hapi_get_hapi_part_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_PartInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_PartId var_id;
    HAPI_StringHandle var_name_sh;
    int var_face_count;
    int var_vertex_count;
    int var_point_count;
    int var_point_attribute_count;
    int var_face_attribute_count;
    int var_vertex_attribute_count;
    int var_detail_attribute_count;
    HAPI_Bool var_has_volume;
    HAPI_Bool var_is_curve;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 12) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_part_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_PartInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_part_info_list(ErlNifEnv* env, const HAPI_PartInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_PartInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_part_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_PartInfo objects from erl to c. */
bool
hapi_get_hapi_part_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_PartInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_PartInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_part_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_MaterialInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_material_info(ErlNifEnv* env, const HAPI_MaterialInfo* hapi_struct)
{
    return enif_make_tuple(env, 6,
        hapi_make_atom(env, "hapi_material_info"),
        hapi_make_hapi_material_id(env, hapi_struct->id),
        hapi_make_hapi_asset_id(env, hapi_struct->assetId),
        hapi_make_hapi_node_id(env, hapi_struct->nodeId),
        hapi_make_hapi_bool(env, hapi_struct->exists),
        hapi_make_hapi_bool(env, hapi_struct->hasChanged));
}


/* Converting HAPI_MaterialInfo from erl to c. */
bool
hapi_get_hapi_material_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_MaterialInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_MaterialId var_id;
    HAPI_AssetId var_asset_id;
    HAPI_NodeId var_node_id;
    HAPI_Bool var_exists;
    HAPI_Bool var_has_changed;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 6) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_material_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_MaterialInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_material_info_list(ErlNifEnv* env, const HAPI_MaterialInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_MaterialInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_material_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_MaterialInfo objects from erl to c. */
bool
hapi_get_hapi_material_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_MaterialInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_MaterialInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_material_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_GlobalNodes from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_global_nodes(ErlNifEnv* env, const HAPI_GlobalNodes* hapi_struct)
{
    return enif_make_tuple(env, 4,
        hapi_make_atom(env, "hapi_global_nodes"),
        hapi_make_hapi_node_id(env, hapi_struct->defaultCamera),
        hapi_make_hapi_node_id(env, hapi_struct->defaultLight),
        hapi_make_hapi_node_id(env, hapi_struct->mantraRenderer));
}


/* Converting HAPI_GlobalNodes from erl to c. */
bool
hapi_get_hapi_global_nodes(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_GlobalNodes* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_NodeId var_default_camera;
    HAPI_NodeId var_default_light;
    HAPI_NodeId var_mantra_renderer;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 4) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_global_nodes", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_GlobalNodes objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_global_nodes_list(ErlNifEnv* env, const HAPI_GlobalNodes* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_GlobalNodes* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_global_nodes(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_GlobalNodes objects from erl to c. */
bool
hapi_get_hapi_global_nodes_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_GlobalNodes* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_GlobalNodes* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_global_nodes(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_HandleBindingInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_handle_binding_info(ErlNifEnv* env, const HAPI_HandleBindingInfo* hapi_struct)
{
    return enif_make_tuple(env, 4,
        hapi_make_atom(env, "hapi_handle_binding_info"),
        hapi_make_hapi_string_handle(env, hapi_struct->handleParmNameSH),
        hapi_make_hapi_string_handle(env, hapi_struct->assetParmNameSH),
        hapi_make_hapi_parm_id(env, hapi_struct->assetParmId));
}


/* Converting HAPI_HandleBindingInfo from erl to c. */
bool
hapi_get_hapi_handle_binding_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_HandleBindingInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_StringHandle var_handle_parm_name_sh;
    HAPI_StringHandle var_asset_parm_name_sh;
    HAPI_ParmId var_asset_parm_id;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 4) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_handle_binding_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_HandleBindingInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_handle_binding_info_list(ErlNifEnv* env, const HAPI_HandleBindingInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_HandleBindingInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_handle_binding_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_HandleBindingInfo objects from erl to c. */
bool
hapi_get_hapi_handle_binding_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_HandleBindingInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_HandleBindingInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_handle_binding_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_ImageInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_image_info(ErlNifEnv* env, const HAPI_ImageInfo* hapi_struct)
{
    return enif_make_tuple(env, 8,
        hapi_make_atom(env, "hapi_image_info"),
        hapi_make_hapi_string_handle(env, hapi_struct->imageFileFormatNameSH),
        hapi_make_int(env, hapi_struct->xRes),
        hapi_make_int(env, hapi_struct->yRes),
        hapi_make_hapi_image_data_format(env, hapi_struct->dataFormat),
        hapi_make_hapi_bool(env, hapi_struct->interleaved),
        hapi_make_hapi_image_packing(env, hapi_struct->packing),
        hapi_make_double(env, hapi_struct->gamma));
}


/* Converting HAPI_ImageInfo from erl to c. */
bool
hapi_get_hapi_image_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ImageInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_StringHandle var_image_file_format_name_sh;
    int var_x_res;
    int var_y_res;
    HAPI_ImageDataFormat var_data_format;
    HAPI_Bool var_interleaved;
    HAPI_ImagePacking var_packing;
    double var_gamma;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 8) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_image_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_ImageInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_image_info_list(ErlNifEnv* env, const HAPI_ImageInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_ImageInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_image_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_ImageInfo objects from erl to c. */
bool
hapi_get_hapi_image_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ImageInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_ImageInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_image_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_VolumeInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_volume_info(ErlNifEnv* env, const HAPI_VolumeInfo* hapi_struct)
{
    return enif_make_tuple(env, 15,
        hapi_make_atom(env, "hapi_volume_info"),
        hapi_make_hapi_string_handle(env, hapi_struct->nameSH),
        hapi_make_int(env, hapi_struct->xLength),
        hapi_make_int(env, hapi_struct->yLength),
        hapi_make_int(env, hapi_struct->zLength),
        hapi_make_int(env, hapi_struct->minX),
        hapi_make_int(env, hapi_struct->minY),
        hapi_make_int(env, hapi_struct->minZ),
        hapi_make_int(env, hapi_struct->tupleSize),
        hapi_make_hapi_storage_type(env, hapi_struct->storage),
        hapi_make_int(env, hapi_struct->tileSize),
        hapi_make_hapi_transform(env, &hapi_struct->transform),
        hapi_make_hapi_bool(env, hapi_struct->hasTaper),
        hapi_make_float(env, hapi_struct->xTaper),
        hapi_make_float(env, hapi_struct->yTaper));
}


/* Converting HAPI_VolumeInfo from erl to c. */
bool
hapi_get_hapi_volume_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_VolumeInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_StringHandle var_name_sh;
    int var_x_length;
    int var_y_length;
    int var_z_length;
    int var_min_x;
    int var_min_y;
    int var_min_z;
    int var_tuple_size;
    HAPI_StorageType var_storage;
    int var_tile_size;
    HAPI_Transform var_transform;
    HAPI_Bool var_has_taper;
    float var_x_taper;
    float var_y_taper;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 15) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_volume_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_VolumeInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_volume_info_list(ErlNifEnv* env, const HAPI_VolumeInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_VolumeInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_volume_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_VolumeInfo objects from erl to c. */
bool
hapi_get_hapi_volume_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_VolumeInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_VolumeInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_volume_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_GeoInputInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_geo_input_info(ErlNifEnv* env, const HAPI_GeoInputInfo* hapi_struct)
{
    return enif_make_tuple(env, 4,
        hapi_make_atom(env, "hapi_geo_input_info"),
        hapi_make_hapi_object_id(env, hapi_struct->objectId),
        hapi_make_hapi_geo_id(env, hapi_struct->geoId),
        hapi_make_hapi_node_id(env, hapi_struct->objectNodeId));
}


/* Converting HAPI_GeoInputInfo from erl to c. */
bool
hapi_get_hapi_geo_input_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_GeoInputInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_ObjectId var_object_id;
    HAPI_GeoId var_geo_id;
    HAPI_NodeId var_object_node_id;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 4) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_geo_input_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_GeoInputInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_geo_input_info_list(ErlNifEnv* env, const HAPI_GeoInputInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_GeoInputInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_geo_input_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_GeoInputInfo objects from erl to c. */
bool
hapi_get_hapi_geo_input_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_GeoInputInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_GeoInputInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_geo_input_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_VolumeTileInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_volume_tile_info(ErlNifEnv* env, const HAPI_VolumeTileInfo* hapi_struct)
{
    return enif_make_tuple(env, 5,
        hapi_make_atom(env, "hapi_volume_tile_info"),
        hapi_make_int(env, hapi_struct->minX),
        hapi_make_int(env, hapi_struct->minY),
        hapi_make_int(env, hapi_struct->minZ),
        hapi_make_hapi_bool(env, hapi_struct->isValid));
}


/* Converting HAPI_VolumeTileInfo from erl to c. */
bool
hapi_get_hapi_volume_tile_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_VolumeTileInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    int var_min_x;
    int var_min_y;
    int var_min_z;
    HAPI_Bool var_is_valid;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 5) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_volume_tile_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_VolumeTileInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_volume_tile_info_list(ErlNifEnv* env, const HAPI_VolumeTileInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_VolumeTileInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_volume_tile_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_VolumeTileInfo objects from erl to c. */
bool
hapi_get_hapi_volume_tile_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_VolumeTileInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_VolumeTileInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_volume_tile_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_CurveInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_curve_info(ErlNifEnv* env, const HAPI_CurveInfo* hapi_struct)
{
    return enif_make_tuple(env, 9,
        hapi_make_atom(env, "hapi_curve_info"),
        hapi_make_hapi_curve_type(env, hapi_struct->curveType),
        hapi_make_int(env, hapi_struct->curveCount),
        hapi_make_int(env, hapi_struct->vertexCount),
        hapi_make_int(env, hapi_struct->knotCount),
        hapi_make_hapi_bool(env, hapi_struct->isPeriodic),
        hapi_make_hapi_bool(env, hapi_struct->isRational),
        hapi_make_int(env, hapi_struct->order),
        hapi_make_hapi_bool(env, hapi_struct->hasKnots));
}


/* Converting HAPI_CurveInfo from erl to c. */
bool
hapi_get_hapi_curve_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_CurveInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_CurveType var_curve_type;
    int var_curve_count;
    int var_vertex_count;
    int var_knot_count;
    HAPI_Bool var_is_periodic;
    HAPI_Bool var_is_rational;
    int var_order;
    HAPI_Bool var_has_knots;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 9) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_curve_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_CurveInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_curve_info_list(ErlNifEnv* env, const HAPI_CurveInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_CurveInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_curve_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_CurveInfo objects from erl to c. */
bool
hapi_get_hapi_curve_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_CurveInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_CurveInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_curve_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_Transform from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_transform(ErlNifEnv* env, const HAPI_Transform* hapi_struct)
{
    return enif_make_tuple(env, 5,
        hapi_make_atom(env, "hapi_transform"),
        hapi_make_float_list(env, &hapi_struct->position[0], 3),
        hapi_make_float_list(env, &hapi_struct->rotationQuaternion[0], 4),
        hapi_make_float_list(env, &hapi_struct->scale[0], 3),
        hapi_make_hapi_rstorder(env, hapi_struct->rstOrder));
}


/* Converting HAPI_Transform from erl to c. */
bool
hapi_get_hapi_transform(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_Transform* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    float var_position[3];
    float var_rotation_quaternion[4];
    float var_scale[3];
    HAPI_RSTOrder var_rst_order;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 5) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_transform", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_Transform objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_transform_list(ErlNifEnv* env, const HAPI_Transform* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_Transform* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_transform(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_Transform objects from erl to c. */
bool
hapi_get_hapi_transform_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_Transform* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_Transform* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_transform(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_ImageFileFormat from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_image_file_format(ErlNifEnv* env, const HAPI_ImageFileFormat* hapi_struct)
{
    return enif_make_tuple(env, 4,
        hapi_make_atom(env, "hapi_image_file_format"),
        hapi_make_hapi_string_handle(env, hapi_struct->nameSH),
        hapi_make_hapi_string_handle(env, hapi_struct->descriptionSH),
        hapi_make_hapi_string_handle(env, hapi_struct->defaultExtensionSH));
}


/* Converting HAPI_ImageFileFormat from erl to c. */
bool
hapi_get_hapi_image_file_format(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ImageFileFormat* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_StringHandle var_name_sh;
    HAPI_StringHandle var_description_sh;
    HAPI_StringHandle var_default_extension_sh;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 4) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_image_file_format", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_ImageFileFormat objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_image_file_format_list(ErlNifEnv* env, const HAPI_ImageFileFormat* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_ImageFileFormat* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_image_file_format(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_ImageFileFormat objects from erl to c. */
bool
hapi_get_hapi_image_file_format_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ImageFileFormat* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_ImageFileFormat* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_image_file_format(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_TransformEuler from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_transform_euler(ErlNifEnv* env, const HAPI_TransformEuler* hapi_struct)
{
    return enif_make_tuple(env, 6,
        hapi_make_atom(env, "hapi_transform_euler"),
        hapi_make_float_list(env, &hapi_struct->position[0], 3),
        hapi_make_float_list(env, &hapi_struct->rotationEuler[0], 3),
        hapi_make_float_list(env, &hapi_struct->scale[0], 3),
        hapi_make_hapi_xyzorder(env, hapi_struct->rotationOrder),
        hapi_make_hapi_rstorder(env, hapi_struct->rstOrder));
}


/* Converting HAPI_TransformEuler from erl to c. */
bool
hapi_get_hapi_transform_euler(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_TransformEuler* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    float var_position[3];
    float var_rotation_euler[3];
    float var_scale[3];
    HAPI_XYZOrder var_rotation_order;
    HAPI_RSTOrder var_rst_order;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 6) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_transform_euler", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_TransformEuler objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_transform_euler_list(ErlNifEnv* env, const HAPI_TransformEuler* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_TransformEuler* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_transform_euler(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_TransformEuler objects from erl to c. */
bool
hapi_get_hapi_transform_euler_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_TransformEuler* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_TransformEuler* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_transform_euler(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_AttributeInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_attribute_info(ErlNifEnv* env, const HAPI_AttributeInfo* hapi_struct)
{
    return enif_make_tuple(env, 7,
        hapi_make_atom(env, "hapi_attribute_info"),
        hapi_make_hapi_bool(env, hapi_struct->exists),
        hapi_make_hapi_attribute_owner(env, hapi_struct->owner),
        hapi_make_hapi_storage_type(env, hapi_struct->storage),
        hapi_make_hapi_attribute_owner(env, hapi_struct->originalOwner),
        hapi_make_int(env, hapi_struct->count),
        hapi_make_int(env, hapi_struct->tupleSize));
}


/* Converting HAPI_AttributeInfo from erl to c. */
bool
hapi_get_hapi_attribute_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_AttributeInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_Bool var_exists;
    HAPI_AttributeOwner var_owner;
    HAPI_StorageType var_storage;
    HAPI_AttributeOwner var_original_owner;
    int var_count;
    int var_tuple_size;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 7) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_attribute_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_AttributeInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_attribute_info_list(ErlNifEnv* env, const HAPI_AttributeInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_AttributeInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_attribute_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_AttributeInfo objects from erl to c. */
bool
hapi_get_hapi_attribute_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_AttributeInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_AttributeInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_attribute_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_GeoInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_geo_info(ErlNifEnv* env, const HAPI_GeoInfo* hapi_struct)
{
    return enif_make_tuple(env, 13,
        hapi_make_atom(env, "hapi_geo_info"),
        hapi_make_hapi_geo_id(env, hapi_struct->id),
        hapi_make_hapi_geo_type(env, hapi_struct->type),
        hapi_make_hapi_string_handle(env, hapi_struct->nameSH),
        hapi_make_hapi_node_id(env, hapi_struct->nodeId),
        hapi_make_hapi_bool(env, hapi_struct->isEditable),
        hapi_make_hapi_bool(env, hapi_struct->isTemplated),
        hapi_make_hapi_bool(env, hapi_struct->isDisplayGeo),
        hapi_make_hapi_bool(env, hapi_struct->hasGeoChanged),
        hapi_make_hapi_bool(env, hapi_struct->hasMaterialChanged),
        hapi_make_int(env, hapi_struct->pointGroupCount),
        hapi_make_int(env, hapi_struct->primitiveGroupCount),
        hapi_make_int(env, hapi_struct->partCount));
}


/* Converting HAPI_GeoInfo from erl to c. */
bool
hapi_get_hapi_geo_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_GeoInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_GeoId var_id;
    HAPI_GeoType var_type;
    HAPI_StringHandle var_name_sh;
    HAPI_NodeId var_node_id;
    HAPI_Bool var_is_editable;
    HAPI_Bool var_is_templated;
    HAPI_Bool var_is_display_geo;
    HAPI_Bool var_has_geo_changed;
    HAPI_Bool var_has_material_changed;
    int var_point_group_count;
    int var_primitive_group_count;
    int var_part_count;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 13) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_geo_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_GeoInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_geo_info_list(ErlNifEnv* env, const HAPI_GeoInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_GeoInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_geo_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_GeoInfo objects from erl to c. */
bool
hapi_get_hapi_geo_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_GeoInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_GeoInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_geo_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_AssetInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_asset_info(ErlNifEnv* env, const HAPI_AssetInfo* hapi_struct)
{
    return enif_make_tuple(env, 20,
        hapi_make_atom(env, "hapi_asset_info"),
        hapi_make_hapi_asset_id(env, hapi_struct->id),
        hapi_make_hapi_asset_type(env, hapi_struct->type),
        hapi_make_hapi_asset_sub_type(env, hapi_struct->subType),
        hapi_make_int(env, hapi_struct->validationId),
        hapi_make_hapi_node_id(env, hapi_struct->nodeId),
        hapi_make_hapi_node_id(env, hapi_struct->objectNodeId),
        hapi_make_hapi_bool(env, hapi_struct->hasEverCooked),
        hapi_make_hapi_string_handle(env, hapi_struct->nameSH),
        hapi_make_hapi_string_handle(env, hapi_struct->labelSH),
        hapi_make_hapi_string_handle(env, hapi_struct->filePathSH),
        hapi_make_hapi_string_handle(env, hapi_struct->versionSH),
        hapi_make_hapi_string_handle(env, hapi_struct->fullOpNameSH),
        hapi_make_hapi_string_handle(env, hapi_struct->helpTextSH),
        hapi_make_int(env, hapi_struct->objectCount),
        hapi_make_int(env, hapi_struct->handleCount),
        hapi_make_int(env, hapi_struct->transformInputCount),
        hapi_make_int(env, hapi_struct->geoInputCount),
        hapi_make_hapi_bool(env, hapi_struct->haveObjectsChanged),
        hapi_make_hapi_bool(env, hapi_struct->haveMaterialsChanged));
}


/* Converting HAPI_AssetInfo from erl to c. */
bool
hapi_get_hapi_asset_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_AssetInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_AssetId var_id;
    HAPI_AssetType var_type;
    HAPI_AssetSubType var_sub_type;
    int var_validation_id;
    HAPI_NodeId var_node_id;
    HAPI_NodeId var_object_node_id;
    HAPI_Bool var_has_ever_cooked;
    HAPI_StringHandle var_name_sh;
    HAPI_StringHandle var_label_sh;
    HAPI_StringHandle var_file_path_sh;
    HAPI_StringHandle var_version_sh;
    HAPI_StringHandle var_full_op_name_sh;
    HAPI_StringHandle var_help_text_sh;
    int var_object_count;
    int var_handle_count;
    int var_transform_input_count;
    int var_geo_input_count;
    HAPI_Bool var_have_objects_changed;
    HAPI_Bool var_have_materials_changed;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 20) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_asset_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_AssetInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_asset_info_list(ErlNifEnv* env, const HAPI_AssetInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_AssetInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_asset_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_AssetInfo objects from erl to c. */
bool
hapi_get_hapi_asset_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_AssetInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_AssetInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_asset_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_ParmChoiceInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_parm_choice_info(ErlNifEnv* env, const HAPI_ParmChoiceInfo* hapi_struct)
{
    return enif_make_tuple(env, 4,
        hapi_make_atom(env, "hapi_parm_choice_info"),
        hapi_make_hapi_parm_id(env, hapi_struct->parentParmId),
        hapi_make_hapi_string_handle(env, hapi_struct->labelSH),
        hapi_make_hapi_string_handle(env, hapi_struct->valueSH));
}


/* Converting HAPI_ParmChoiceInfo from erl to c. */
bool
hapi_get_hapi_parm_choice_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ParmChoiceInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_ParmId var_parent_parm_id;
    HAPI_StringHandle var_label_sh;
    HAPI_StringHandle var_value_sh;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 4) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_parm_choice_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_ParmChoiceInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_parm_choice_info_list(ErlNifEnv* env, const HAPI_ParmChoiceInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_ParmChoiceInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_parm_choice_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_ParmChoiceInfo objects from erl to c. */
bool
hapi_get_hapi_parm_choice_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ParmChoiceInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_ParmChoiceInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_parm_choice_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_ObjectInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_object_info(ErlNifEnv* env, const HAPI_ObjectInfo* hapi_struct)
{
    return enif_make_tuple(env, 11,
        hapi_make_atom(env, "hapi_object_info"),
        hapi_make_hapi_object_id(env, hapi_struct->id),
        hapi_make_hapi_string_handle(env, hapi_struct->nameSH),
        hapi_make_hapi_string_handle(env, hapi_struct->objectInstancePathSH),
        hapi_make_hapi_bool(env, hapi_struct->hasTransformChanged),
        hapi_make_hapi_bool(env, hapi_struct->haveGeosChanged),
        hapi_make_hapi_bool(env, hapi_struct->isVisible),
        hapi_make_hapi_bool(env, hapi_struct->isInstancer),
        hapi_make_int(env, hapi_struct->geoCount),
        hapi_make_hapi_node_id(env, hapi_struct->nodeId),
        hapi_make_hapi_object_id(env, hapi_struct->objectToInstanceId));
}


/* Converting HAPI_ObjectInfo from erl to c. */
bool
hapi_get_hapi_object_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ObjectInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_ObjectId var_id;
    HAPI_StringHandle var_name_sh;
    HAPI_StringHandle var_object_instance_path_sh;
    HAPI_Bool var_has_transform_changed;
    HAPI_Bool var_have_geos_changed;
    HAPI_Bool var_is_visible;
    HAPI_Bool var_is_instancer;
    int var_geo_count;
    HAPI_NodeId var_node_id;
    HAPI_ObjectId var_object_to_instance_id;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 11) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_object_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_ObjectInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_object_info_list(ErlNifEnv* env, const HAPI_ObjectInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_ObjectInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_object_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_ObjectInfo objects from erl to c. */
bool
hapi_get_hapi_object_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ObjectInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_ObjectInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_object_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_HandleInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_handle_info(ErlNifEnv* env, const HAPI_HandleInfo* hapi_struct)
{
    return enif_make_tuple(env, 4,
        hapi_make_atom(env, "hapi_handle_info"),
        hapi_make_hapi_string_handle(env, hapi_struct->nameSH),
        hapi_make_hapi_string_handle(env, hapi_struct->typeNameSH),
        hapi_make_int(env, hapi_struct->bindingsCount));
}


/* Converting HAPI_HandleInfo from erl to c. */
bool
hapi_get_hapi_handle_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_HandleInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_StringHandle var_name_sh;
    HAPI_StringHandle var_type_name_sh;
    int var_bindings_count;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 4) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_handle_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_HandleInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_handle_info_list(ErlNifEnv* env, const HAPI_HandleInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_HandleInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_handle_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_HandleInfo objects from erl to c. */
bool
hapi_get_hapi_handle_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_HandleInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_HandleInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_handle_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_TimelineOptions from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_timeline_options(ErlNifEnv* env, const HAPI_TimelineOptions* hapi_struct)
{
    return enif_make_tuple(env, 4,
        hapi_make_atom(env, "hapi_timeline_options"),
        hapi_make_float(env, hapi_struct->fps),
        hapi_make_float(env, hapi_struct->startTime),
        hapi_make_float(env, hapi_struct->endTime));
}


/* Converting HAPI_TimelineOptions from erl to c. */
bool
hapi_get_hapi_timeline_options(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_TimelineOptions* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    float var_fps;
    float var_start_time;
    float var_end_time;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 4) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_timeline_options", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_TimelineOptions objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_timeline_options_list(ErlNifEnv* env, const HAPI_TimelineOptions* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_TimelineOptions* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_timeline_options(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_TimelineOptions objects from erl to c. */
bool
hapi_get_hapi_timeline_options_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_TimelineOptions* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_TimelineOptions* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_timeline_options(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_NodeInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_node_info(ErlNifEnv* env, const HAPI_NodeInfo* hapi_struct)
{
    return enif_make_tuple(env, 12,
        hapi_make_atom(env, "hapi_node_info"),
        hapi_make_hapi_node_id(env, hapi_struct->id),
        hapi_make_hapi_asset_id(env, hapi_struct->assetId),
        hapi_make_hapi_string_handle(env, hapi_struct->nameSH),
        hapi_make_int(env, hapi_struct->totalCookCount),
        hapi_make_int(env, hapi_struct->uniqueHoudiniNodeId),
        hapi_make_hapi_string_handle(env, hapi_struct->internalNodePathSH),
        hapi_make_int(env, hapi_struct->parmCount),
        hapi_make_int(env, hapi_struct->parmIntValueCount),
        hapi_make_int(env, hapi_struct->parmFloatValueCount),
        hapi_make_int(env, hapi_struct->parmStringValueCount),
        hapi_make_int(env, hapi_struct->parmChoiceCount));
}


/* Converting HAPI_NodeInfo from erl to c. */
bool
hapi_get_hapi_node_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_NodeInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_NodeId var_id;
    HAPI_AssetId var_asset_id;
    HAPI_StringHandle var_name_sh;
    int var_total_cook_count;
    int var_unique_houdini_node_id;
    HAPI_StringHandle var_internal_node_path_sh;
    int var_parm_count;
    int var_parm_int_value_count;
    int var_parm_float_value_count;
    int var_parm_string_value_count;
    int var_parm_choice_count;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 12) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_node_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_NodeInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_node_info_list(ErlNifEnv* env, const HAPI_NodeInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_NodeInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_node_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_NodeInfo objects from erl to c. */
bool
hapi_get_hapi_node_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_NodeInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_NodeInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_node_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

/* Converting HAPI_ParmInfo from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_parm_info(ErlNifEnv* env, const HAPI_ParmInfo* hapi_struct)
{
    return enif_make_tuple(env, 35,
        hapi_make_atom(env, "hapi_parm_info"),
        hapi_make_hapi_parm_id(env, hapi_struct->id),
        hapi_make_hapi_parm_id(env, hapi_struct->parentId),
        hapi_make_hapi_parm_type(env, hapi_struct->type),
        hapi_make_hapi_string_handle(env, hapi_struct->typeInfoSH),
        hapi_make_hapi_permissions(env, hapi_struct->permissions),
        hapi_make_int(env, hapi_struct->size),
        hapi_make_int(env, hapi_struct->choiceCount),
        hapi_make_hapi_string_handle(env, hapi_struct->nameSH),
        hapi_make_hapi_string_handle(env, hapi_struct->labelSH),
        hapi_make_hapi_string_handle(env, hapi_struct->templateNameSH),
        hapi_make_hapi_string_handle(env, hapi_struct->helpSH),
        hapi_make_hapi_bool(env, hapi_struct->hasMin),
        hapi_make_hapi_bool(env, hapi_struct->hasMax),
        hapi_make_hapi_bool(env, hapi_struct->hasUIMin),
        hapi_make_hapi_bool(env, hapi_struct->hasUIMax),
        hapi_make_float(env, hapi_struct->min),
        hapi_make_float(env, hapi_struct->max),
        hapi_make_float(env, hapi_struct->UIMin),
        hapi_make_float(env, hapi_struct->UIMax),
        hapi_make_hapi_bool(env, hapi_struct->invisible),
        hapi_make_hapi_bool(env, hapi_struct->disabled),
        hapi_make_hapi_bool(env, hapi_struct->spare),
        hapi_make_hapi_bool(env, hapi_struct->joinNext),
        hapi_make_hapi_bool(env, hapi_struct->labelNone),
        hapi_make_int(env, hapi_struct->intValuesIndex),
        hapi_make_int(env, hapi_struct->floatValuesIndex),
        hapi_make_int(env, hapi_struct->stringValuesIndex),
        hapi_make_int(env, hapi_struct->choiceIndex),
        hapi_make_hapi_bool(env, hapi_struct->isChildOfMultiParm),
        hapi_make_int(env, hapi_struct->instanceNum),
        hapi_make_int(env, hapi_struct->instanceLength),
        hapi_make_int(env, hapi_struct->instanceCount),
        hapi_make_int(env, hapi_struct->instanceStartOffset),
        hapi_make_hapi_ramp_type(env, hapi_struct->rampType));
}


/* Converting HAPI_ParmInfo from erl to c. */
bool
hapi_get_hapi_parm_info(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ParmInfo* hapi_struct)
{
    int32_t tuple_size = 0;
    const ERL_NIF_TERM* tuple_record = NULL;
    bool atom_name_match = false;

    HAPI_ParmId var_id;
    HAPI_ParmId var_parent_id;
    HAPI_ParmType var_type;
    HAPI_StringHandle var_type_info_sh;
    HAPI_Permissions var_permissions;
    int var_size;
    int var_choice_count;
    HAPI_StringHandle var_name_sh;
    HAPI_StringHandle var_label_sh;
    HAPI_StringHandle var_template_name_sh;
    HAPI_StringHandle var_help_sh;
    HAPI_Bool var_has_min;
    HAPI_Bool var_has_max;
    HAPI_Bool var_has_uimin;
    HAPI_Bool var_has_uimax;
    float var_min;
    float var_max;
    float var_uimin;
    float var_uimax;
    HAPI_Bool var_invisible;
    HAPI_Bool var_disabled;
    HAPI_Bool var_spare;
    HAPI_Bool var_join_next;
    HAPI_Bool var_label_none;
    int var_int_values_index;
    int var_float_values_index;
    int var_string_values_index;
    int var_choice_index;
    HAPI_Bool var_is_child_of_multi_parm;
    int var_instance_num;
    int var_instance_length;
    int var_instance_count;
    int var_instance_start_offset;
    HAPI_RampType var_ramp_type;

    if(!enif_get_tuple(env, term, &tuple_size, &tuple_record) ||
        (tuple_size != 35) ||
        !hapi_check_atom(env, tuple_record[0], "hapi_parm_info", &atom_name_match) ||
        !atom_name_match ||
        %{HAPI_STRUCT_TO_C_MAP}%)
    {
        return false;
    }

    %{HAPI_STRUCT_TO_C_ASSIGN}%

    return true;
}


/* Converting array of HAPI_ParmInfo objects from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_parm_info_list(ErlNifEnv* env, const HAPI_ParmInfo* hapi_structs, uint32_t list_size)
{
    ERL_NIF_TERM list = enif_make_list(env, 0);

    for(int32_t idx = list_size - 1; idx >= 0; idx--)
    {
        const HAPI_ParmInfo* hapi_struct = hapi_structs + idx;
        list = enif_make_list_cell(env, hapi_make_hapi_parm_info(env, hapi_struct), list);
    }

    return list;
}


/* Converting list of HAPI_ParmInfo objects from erl to c. */
bool
hapi_get_hapi_parm_info_list(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ParmInfo* hapi_structs, uint32_t list_size)
{
    uint32_t read_list_size = 0;
    ERL_NIF_TERM head, tail;

    if(enif_get_list_length(env, term, &read_list_size) && (list_size == read_list_size))
    {
        ERL_NIF_TERM list = term;
        int32_t index = 0;

        while(enif_get_list_cell(env, list, &head, &tail))
        {
            HAPI_ParmInfo* hapi_struct = hapi_structs + index;

            if(!hapi_get_hapi_parm_info(env, head, hapi_struct))
            {
                return false;
            }

            index++;
            list = tail;
        }

        return true;
    }

    return false;
}

