/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enums_nif.c.template

#include "hapi_private_nif.h"
#include "hapi_enums_nif.h"
#include <string.h>


/* Converting HAPI_RampType from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_ramp_type(ErlNifEnv* env, HAPI_RampType enum_value)
{
    switch(enum_value)
    {
        case HAPI_RAMPTYPE_INVALID:
        {
            return hapi_make_atom(env, "hapi_ramptype_invalid");
        }

        case HAPI_RAMPTYPE_FLOAT:
        {
            return hapi_make_atom(env, "hapi_ramptype_float");
        }

        case HAPI_RAMPTYPE_COLOR:
        {
            return hapi_make_atom(env, "hapi_ramptype_color");
        }

        case HAPI_RAMPTYPE_MAX:
        {
            return hapi_make_atom(env, "hapi_ramptype_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_RampType from erl to c. */
bool
hapi_get_hapi_ramp_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_RampType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_ramptype_invalid */
        case 1007057020:
        {
            *enum_result = HAPI_RAMPTYPE_INVALID;
            break;
        }

        /* hapi_ramptype_float */
        case 1236730525:
        {
            *enum_result = HAPI_RAMPTYPE_FLOAT;
            break;
        }

        /* hapi_ramptype_color */
        case 784329284:
        {
            *enum_result = HAPI_RAMPTYPE_COLOR;
            break;
        }

        /* hapi_ramptype_max */
        case 1883049949:
        {
            *enum_result = HAPI_RAMPTYPE_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_XYZOrder from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_xyzorder(ErlNifEnv* env, HAPI_XYZOrder enum_value)
{
    switch(enum_value)
    {
        case HAPI_XYZ:
        {
            return hapi_make_atom(env, "hapi_xyz");
        }

        case HAPI_XZY:
        {
            return hapi_make_atom(env, "hapi_xzy");
        }

        case HAPI_YXZ:
        {
            return hapi_make_atom(env, "hapi_yxz");
        }

        case HAPI_YZX:
        {
            return hapi_make_atom(env, "hapi_yzx");
        }

        case HAPI_ZXY:
        {
            return hapi_make_atom(env, "hapi_zxy");
        }

        case HAPI_ZYX:
        {
            return hapi_make_atom(env, "hapi_zyx");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_XYZOrder from erl to c. */
bool
hapi_get_hapi_xyzorder(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_XYZOrder* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_xyz */
        case 2568995979:
        {
            *enum_result = HAPI_XYZ;
            break;
        }

        /* hapi_xzy */
        case 3456057817:
        {
            *enum_result = HAPI_XZY;
            break;
        }

        /* hapi_yxz */
        case 535519317:
        {
            *enum_result = HAPI_YXZ;
            break;
        }

        /* hapi_yzx */
        case 2498703819:
        {
            *enum_result = HAPI_YZX;
            break;
        }

        /* hapi_zxy */
        case 4080643183:
        {
            *enum_result = HAPI_ZXY;
            break;
        }

        /* hapi_zyx */
        case 2804301731:
        {
            *enum_result = HAPI_ZYX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_ImageDataFormat from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_image_data_format(ErlNifEnv* env, HAPI_ImageDataFormat enum_value)
{
    switch(enum_value)
    {
        case HAPI_IMAGE_DATA_UNKNOWN:
        {
            return hapi_make_atom(env, "hapi_image_data_unknown");
        }

        case HAPI_IMAGE_DATA_INT8:
        {
            return hapi_make_atom(env, "hapi_image_data_int8");
        }

        case HAPI_IMAGE_DATA_INT16:
        {
            return hapi_make_atom(env, "hapi_image_data_int16");
        }

        case HAPI_IMAGE_DATA_INT32:
        {
            return hapi_make_atom(env, "hapi_image_data_int32");
        }

        case HAPI_IMAGE_DATA_FLOAT16:
        {
            return hapi_make_atom(env, "hapi_image_data_float16");
        }

        case HAPI_IMAGE_DATA_FLOAT32:
        {
            return hapi_make_atom(env, "hapi_image_data_float32");
        }

        case HAPI_IMAGE_DATA_MAX:
        {
            return hapi_make_atom(env, "hapi_image_data_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_ImageDataFormat from erl to c. */
bool
hapi_get_hapi_image_data_format(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ImageDataFormat* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_image_data_unknown */
        case 295456066:
        {
            *enum_result = HAPI_IMAGE_DATA_UNKNOWN;
            break;
        }

        /* hapi_image_data_int8 */
        case 261911782:
        {
            *enum_result = HAPI_IMAGE_DATA_INT8;
            break;
        }

        /* hapi_image_data_int16 */
        case 3832188088:
        {
            *enum_result = HAPI_IMAGE_DATA_INT16;
            break;
        }

        /* hapi_image_data_int32 */
        case 2365989835:
        {
            *enum_result = HAPI_IMAGE_DATA_INT32;
            break;
        }

        /* hapi_image_data_float16 */
        case 3680643574:
        {
            *enum_result = HAPI_IMAGE_DATA_FLOAT16;
            break;
        }

        /* hapi_image_data_float32 */
        case 1193977332:
        {
            *enum_result = HAPI_IMAGE_DATA_FLOAT32;
            break;
        }

        /* hapi_image_data_max */
        case 3576233170:
        {
            *enum_result = HAPI_IMAGE_DATA_MAX;
            break;
        }

        /* hapi_image_data_default */
        case 3085908946:
        {
            *enum_result = HAPI_IMAGE_DATA_DEFAULT;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_License from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_license(ErlNifEnv* env, HAPI_License enum_value)
{
    switch(enum_value)
    {
        case HAPI_LICENSE_NONE:
        {
            return hapi_make_atom(env, "hapi_license_none");
        }

        case HAPI_LICENSE_HOUDINI_ENGINE:
        {
            return hapi_make_atom(env, "hapi_license_houdini_engine");
        }

        case HAPI_LICENSE_HOUDINI:
        {
            return hapi_make_atom(env, "hapi_license_houdini");
        }

        case HAPI_LICENSE_HOUDINI_FX:
        {
            return hapi_make_atom(env, "hapi_license_houdini_fx");
        }

        case HAPI_LICENSE_HOUDINI_ENGINE_INDIE:
        {
            return hapi_make_atom(env, "hapi_license_houdini_engine_indie");
        }

        case HAPI_LICENSE_HOUDINI_INDIE:
        {
            return hapi_make_atom(env, "hapi_license_houdini_indie");
        }

        case HAPI_LICENSE_MAX:
        {
            return hapi_make_atom(env, "hapi_license_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_License from erl to c. */
bool
hapi_get_hapi_license(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_License* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_license_none */
        case 2752421224:
        {
            *enum_result = HAPI_LICENSE_NONE;
            break;
        }

        /* hapi_license_houdini_engine */
        case 3778753798:
        {
            *enum_result = HAPI_LICENSE_HOUDINI_ENGINE;
            break;
        }

        /* hapi_license_houdini */
        case 1639045708:
        {
            *enum_result = HAPI_LICENSE_HOUDINI;
            break;
        }

        /* hapi_license_houdini_fx */
        case 2615467121:
        {
            *enum_result = HAPI_LICENSE_HOUDINI_FX;
            break;
        }

        /* hapi_license_houdini_engine_indie */
        case 4087197588:
        {
            *enum_result = HAPI_LICENSE_HOUDINI_ENGINE_INDIE;
            break;
        }

        /* hapi_license_houdini_indie */
        case 238988394:
        {
            *enum_result = HAPI_LICENSE_HOUDINI_INDIE;
            break;
        }

        /* hapi_license_max */
        case 1885498993:
        {
            *enum_result = HAPI_LICENSE_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_GeoType from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_geo_type(ErlNifEnv* env, HAPI_GeoType enum_value)
{
    switch(enum_value)
    {
        case HAPI_GEOTYPE_INVALID:
        {
            return hapi_make_atom(env, "hapi_geotype_invalid");
        }

        case HAPI_GEOTYPE_DEFAULT:
        {
            return hapi_make_atom(env, "hapi_geotype_default");
        }

        case HAPI_GEOTYPE_INTERMEDIATE:
        {
            return hapi_make_atom(env, "hapi_geotype_intermediate");
        }

        case HAPI_GEOTYPE_INPUT:
        {
            return hapi_make_atom(env, "hapi_geotype_input");
        }

        case HAPI_GEOTYPE_CURVE:
        {
            return hapi_make_atom(env, "hapi_geotype_curve");
        }

        case HAPI_GEOTYPE_MAX:
        {
            return hapi_make_atom(env, "hapi_geotype_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_GeoType from erl to c. */
bool
hapi_get_hapi_geo_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_GeoType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_geotype_invalid */
        case 2078624117:
        {
            *enum_result = HAPI_GEOTYPE_INVALID;
            break;
        }

        /* hapi_geotype_default */
        case 1702122176:
        {
            *enum_result = HAPI_GEOTYPE_DEFAULT;
            break;
        }

        /* hapi_geotype_intermediate */
        case 2057813327:
        {
            *enum_result = HAPI_GEOTYPE_INTERMEDIATE;
            break;
        }

        /* hapi_geotype_input */
        case 3505553948:
        {
            *enum_result = HAPI_GEOTYPE_INPUT;
            break;
        }

        /* hapi_geotype_curve */
        case 3589938837:
        {
            *enum_result = HAPI_GEOTYPE_CURVE;
            break;
        }

        /* hapi_geotype_max */
        case 2561471983:
        {
            *enum_result = HAPI_GEOTYPE_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_InputType from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_input_type(ErlNifEnv* env, HAPI_InputType enum_value)
{
    switch(enum_value)
    {
        case HAPI_INPUT_INVALID:
        {
            return hapi_make_atom(env, "hapi_input_invalid");
        }

        case HAPI_INPUT_TRANSFORM:
        {
            return hapi_make_atom(env, "hapi_input_transform");
        }

        case HAPI_INPUT_GEOMETRY:
        {
            return hapi_make_atom(env, "hapi_input_geometry");
        }

        case HAPI_INPUT_MAX:
        {
            return hapi_make_atom(env, "hapi_input_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_InputType from erl to c. */
bool
hapi_get_hapi_input_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_InputType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_input_invalid */
        case 831007676:
        {
            *enum_result = HAPI_INPUT_INVALID;
            break;
        }

        /* hapi_input_transform */
        case 1095021568:
        {
            *enum_result = HAPI_INPUT_TRANSFORM;
            break;
        }

        /* hapi_input_geometry */
        case 2583127688:
        {
            *enum_result = HAPI_INPUT_GEOMETRY;
            break;
        }

        /* hapi_input_max */
        case 4193495948:
        {
            *enum_result = HAPI_INPUT_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_AssetType from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_asset_type(ErlNifEnv* env, HAPI_AssetType enum_value)
{
    switch(enum_value)
    {
        case HAPI_ASSETTYPE_INVALID:
        {
            return hapi_make_atom(env, "hapi_assettype_invalid");
        }

        case HAPI_ASSETTYPE_OBJ:
        {
            return hapi_make_atom(env, "hapi_assettype_obj");
        }

        case HAPI_ASSETTYPE_SOP:
        {
            return hapi_make_atom(env, "hapi_assettype_sop");
        }

        case HAPI_ASSETTYPE_POPNET:
        {
            return hapi_make_atom(env, "hapi_assettype_popnet");
        }

        case HAPI_ASSETTYPE_POP:
        {
            return hapi_make_atom(env, "hapi_assettype_pop");
        }

        case HAPI_ASSETTYPE_CHOPNET:
        {
            return hapi_make_atom(env, "hapi_assettype_chopnet");
        }

        case HAPI_ASSETTYPE_CHOP:
        {
            return hapi_make_atom(env, "hapi_assettype_chop");
        }

        case HAPI_ASSETTYPE_ROP:
        {
            return hapi_make_atom(env, "hapi_assettype_rop");
        }

        case HAPI_ASSETTYPE_SHOP:
        {
            return hapi_make_atom(env, "hapi_assettype_shop");
        }

        case HAPI_ASSETTYPE_COP2:
        {
            return hapi_make_atom(env, "hapi_assettype_cop2");
        }

        case HAPI_ASSETTYPE_COPNET:
        {
            return hapi_make_atom(env, "hapi_assettype_copnet");
        }

        case HAPI_ASSETTYPE_VOP:
        {
            return hapi_make_atom(env, "hapi_assettype_vop");
        }

        case HAPI_ASSETTYPE_VOPNET:
        {
            return hapi_make_atom(env, "hapi_assettype_vopnet");
        }

        case HAPI_ASSETTYPE_DOP:
        {
            return hapi_make_atom(env, "hapi_assettype_dop");
        }

        case HAPI_ASSETTYPE_MGR:
        {
            return hapi_make_atom(env, "hapi_assettype_mgr");
        }

        case HAPI_ASSETTYPE_DIR:
        {
            return hapi_make_atom(env, "hapi_assettype_dir");
        }

        case HAPI_ASSETTYPE_MAX:
        {
            return hapi_make_atom(env, "hapi_assettype_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_AssetType from erl to c. */
bool
hapi_get_hapi_asset_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_AssetType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_assettype_invalid */
        case 3266553345:
        {
            *enum_result = HAPI_ASSETTYPE_INVALID;
            break;
        }

        /* hapi_assettype_obj */
        case 3893167597:
        {
            *enum_result = HAPI_ASSETTYPE_OBJ;
            break;
        }

        /* hapi_assettype_sop */
        case 1581980326:
        {
            *enum_result = HAPI_ASSETTYPE_SOP;
            break;
        }

        /* hapi_assettype_popnet */
        case 870436306:
        {
            *enum_result = HAPI_ASSETTYPE_POPNET;
            break;
        }

        /* hapi_assettype_pop */
        case 3433094276:
        {
            *enum_result = HAPI_ASSETTYPE_POP;
            break;
        }

        /* hapi_assettype_chopnet */
        case 1965316406:
        {
            *enum_result = HAPI_ASSETTYPE_CHOPNET;
            break;
        }

        /* hapi_assettype_chop */
        case 2466487462:
        {
            *enum_result = HAPI_ASSETTYPE_CHOP;
            break;
        }

        /* hapi_assettype_rop */
        case 523518409:
        {
            *enum_result = HAPI_ASSETTYPE_ROP;
            break;
        }

        /* hapi_assettype_shop */
        case 3062776791:
        {
            *enum_result = HAPI_ASSETTYPE_SHOP;
            break;
        }

        /* hapi_assettype_cop2 */
        case 3777195680:
        {
            *enum_result = HAPI_ASSETTYPE_COP2;
            break;
        }

        /* hapi_assettype_copnet */
        case 3179476083:
        {
            *enum_result = HAPI_ASSETTYPE_COPNET;
            break;
        }

        /* hapi_assettype_vop */
        case 3357604912:
        {
            *enum_result = HAPI_ASSETTYPE_VOP;
            break;
        }

        /* hapi_assettype_vopnet */
        case 3064806235:
        {
            *enum_result = HAPI_ASSETTYPE_VOPNET;
            break;
        }

        /* hapi_assettype_dop */
        case 4248199486:
        {
            *enum_result = HAPI_ASSETTYPE_DOP;
            break;
        }

        /* hapi_assettype_mgr */
        case 1777286259:
        {
            *enum_result = HAPI_ASSETTYPE_MGR;
            break;
        }

        /* hapi_assettype_dir */
        case 3193664342:
        {
            *enum_result = HAPI_ASSETTYPE_DIR;
            break;
        }

        /* hapi_assettype_max */
        case 483989670:
        {
            *enum_result = HAPI_ASSETTYPE_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_RSTOrder from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_rstorder(ErlNifEnv* env, HAPI_RSTOrder enum_value)
{
    switch(enum_value)
    {
        case HAPI_TRS:
        {
            return hapi_make_atom(env, "hapi_trs");
        }

        case HAPI_TSR:
        {
            return hapi_make_atom(env, "hapi_tsr");
        }

        case HAPI_RTS:
        {
            return hapi_make_atom(env, "hapi_rts");
        }

        case HAPI_RST:
        {
            return hapi_make_atom(env, "hapi_rst");
        }

        case HAPI_STR:
        {
            return hapi_make_atom(env, "hapi_str");
        }

        case HAPI_SRT:
        {
            return hapi_make_atom(env, "hapi_srt");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_RSTOrder from erl to c. */
bool
hapi_get_hapi_rstorder(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_RSTOrder* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_trs */
        case 2754525809:
        {
            *enum_result = HAPI_TRS;
            break;
        }

        /* hapi_tsr */
        case 1637507022:
        {
            *enum_result = HAPI_TSR;
            break;
        }

        /* hapi_rts */
        case 813138616:
        {
            *enum_result = HAPI_RTS;
            break;
        }

        /* hapi_rst */
        case 3620151878:
        {
            *enum_result = HAPI_RST;
            break;
        }

        /* hapi_str */
        case 531899175:
        {
            *enum_result = HAPI_STR;
            break;
        }

        /* hapi_srt */
        case 169178964:
        {
            *enum_result = HAPI_SRT;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_AttributeOwner from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_attribute_owner(ErlNifEnv* env, HAPI_AttributeOwner enum_value)
{
    switch(enum_value)
    {
        case HAPI_ATTROWNER_INVALID:
        {
            return hapi_make_atom(env, "hapi_attrowner_invalid");
        }

        case HAPI_ATTROWNER_VERTEX:
        {
            return hapi_make_atom(env, "hapi_attrowner_vertex");
        }

        case HAPI_ATTROWNER_POINT:
        {
            return hapi_make_atom(env, "hapi_attrowner_point");
        }

        case HAPI_ATTROWNER_PRIM:
        {
            return hapi_make_atom(env, "hapi_attrowner_prim");
        }

        case HAPI_ATTROWNER_DETAIL:
        {
            return hapi_make_atom(env, "hapi_attrowner_detail");
        }

        case HAPI_ATTROWNER_MAX:
        {
            return hapi_make_atom(env, "hapi_attrowner_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_AttributeOwner from erl to c. */
bool
hapi_get_hapi_attribute_owner(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_AttributeOwner* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_attrowner_invalid */
        case 679692306:
        {
            *enum_result = HAPI_ATTROWNER_INVALID;
            break;
        }

        /* hapi_attrowner_vertex */
        case 3318397195:
        {
            *enum_result = HAPI_ATTROWNER_VERTEX;
            break;
        }

        /* hapi_attrowner_point */
        case 902726316:
        {
            *enum_result = HAPI_ATTROWNER_POINT;
            break;
        }

        /* hapi_attrowner_prim */
        case 3208328655:
        {
            *enum_result = HAPI_ATTROWNER_PRIM;
            break;
        }

        /* hapi_attrowner_detail */
        case 1131849991:
        {
            *enum_result = HAPI_ATTROWNER_DETAIL;
            break;
        }

        /* hapi_attrowner_max */
        case 4198344184:
        {
            *enum_result = HAPI_ATTROWNER_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_ShaderType from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_shader_type(ErlNifEnv* env, HAPI_ShaderType enum_value)
{
    switch(enum_value)
    {
        case HAPI_SHADER_INVALID:
        {
            return hapi_make_atom(env, "hapi_shader_invalid");
        }

        case HAPI_SHADER_OPENGL:
        {
            return hapi_make_atom(env, "hapi_shader_opengl");
        }

        case HAPI_SHADER_MANTRA:
        {
            return hapi_make_atom(env, "hapi_shader_mantra");
        }

        case HAPI_SHADER_MAX:
        {
            return hapi_make_atom(env, "hapi_shader_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_ShaderType from erl to c. */
bool
hapi_get_hapi_shader_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ShaderType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_shader_invalid */
        case 1767885971:
        {
            *enum_result = HAPI_SHADER_INVALID;
            break;
        }

        /* hapi_shader_opengl */
        case 172551974:
        {
            *enum_result = HAPI_SHADER_OPENGL;
            break;
        }

        /* hapi_shader_mantra */
        case 2307354241:
        {
            *enum_result = HAPI_SHADER_MANTRA;
            break;
        }

        /* hapi_shader_max */
        case 2683922648:
        {
            *enum_result = HAPI_SHADER_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_ImagePacking from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_image_packing(ErlNifEnv* env, HAPI_ImagePacking enum_value)
{
    switch(enum_value)
    {
        case HAPI_IMAGE_PACKING_UNKNOWN:
        {
            return hapi_make_atom(env, "hapi_image_packing_unknown");
        }

        case HAPI_IMAGE_PACKING_SINGLE:
        {
            return hapi_make_atom(env, "hapi_image_packing_single");
        }

        case HAPI_IMAGE_PACKING_DUAL:
        {
            return hapi_make_atom(env, "hapi_image_packing_dual");
        }

        case HAPI_IMAGE_PACKING_RGB:
        {
            return hapi_make_atom(env, "hapi_image_packing_rgb");
        }

        case HAPI_IMAGE_PACKING_BGR:
        {
            return hapi_make_atom(env, "hapi_image_packing_bgr");
        }

        case HAPI_IMAGE_PACKING_RGBA:
        {
            return hapi_make_atom(env, "hapi_image_packing_rgba");
        }

        case HAPI_IMAGE_PACKING_ABGR:
        {
            return hapi_make_atom(env, "hapi_image_packing_abgr");
        }

        case HAPI_IMAGE_PACKING_MAX:
        {
            return hapi_make_atom(env, "hapi_image_packing_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_ImagePacking from erl to c. */
bool
hapi_get_hapi_image_packing(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ImagePacking* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_image_packing_unknown */
        case 1026533579:
        {
            *enum_result = HAPI_IMAGE_PACKING_UNKNOWN;
            break;
        }

        /* hapi_image_packing_single */
        case 4027772177:
        {
            *enum_result = HAPI_IMAGE_PACKING_SINGLE;
            break;
        }

        /* hapi_image_packing_dual */
        case 3618580164:
        {
            *enum_result = HAPI_IMAGE_PACKING_DUAL;
            break;
        }

        /* hapi_image_packing_rgb */
        case 1954788252:
        {
            *enum_result = HAPI_IMAGE_PACKING_RGB;
            break;
        }

        /* hapi_image_packing_bgr */
        case 3355295031:
        {
            *enum_result = HAPI_IMAGE_PACKING_BGR;
            break;
        }

        /* hapi_image_packing_rgba */
        case 211676614:
        {
            *enum_result = HAPI_IMAGE_PACKING_RGBA;
            break;
        }

        /* hapi_image_packing_abgr */
        case 4154788832:
        {
            *enum_result = HAPI_IMAGE_PACKING_ABGR;
            break;
        }

        /* hapi_image_packing_max */
        case 2046891834:
        {
            *enum_result = HAPI_IMAGE_PACKING_MAX;
            break;
        }

        /* hapi_image_packing_default3 */
        case 3652598404:
        {
            *enum_result = HAPI_IMAGE_PACKING_DEFAULT3;
            break;
        }

        /* hapi_image_packing_default4 */
        case 1347420588:
        {
            *enum_result = HAPI_IMAGE_PACKING_DEFAULT4;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_Result from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_result(ErlNifEnv* env, HAPI_Result enum_value)
{
    switch(enum_value)
    {
        case HAPI_RESULT_SUCCESS:
        {
            return hapi_make_atom(env, "hapi_result_success");
        }

        case HAPI_RESULT_FAILURE:
        {
            return hapi_make_atom(env, "hapi_result_failure");
        }

        case HAPI_RESULT_ALREADY_INITIALIZED:
        {
            return hapi_make_atom(env, "hapi_result_already_initialized");
        }

        case HAPI_RESULT_NOT_INITIALIZED:
        {
            return hapi_make_atom(env, "hapi_result_not_initialized");
        }

        case HAPI_RESULT_CANT_LOADFILE:
        {
            return hapi_make_atom(env, "hapi_result_cant_loadfile");
        }

        case HAPI_RESULT_PARM_SET_FAILED:
        {
            return hapi_make_atom(env, "hapi_result_parm_set_failed");
        }

        case HAPI_RESULT_INVALID_ARGUMENT:
        {
            return hapi_make_atom(env, "hapi_result_invalid_argument");
        }

        case HAPI_RESULT_CANT_LOAD_GEO:
        {
            return hapi_make_atom(env, "hapi_result_cant_load_geo");
        }

        case HAPI_RESULT_CANT_GENERATE_PRESET:
        {
            return hapi_make_atom(env, "hapi_result_cant_generate_preset");
        }

        case HAPI_RESULT_CANT_LOAD_PRESET:
        {
            return hapi_make_atom(env, "hapi_result_cant_load_preset");
        }

        case HAPI_RESULT_ASSET_DEF_ALREADY_LOADED:
        {
            return hapi_make_atom(env, "hapi_result_asset_def_already_loaded");
        }

        case HAPI_RESULT_NO_LICENSE_FOUND:
        {
            return hapi_make_atom(env, "hapi_result_no_license_found");
        }

        case HAPI_RESULT_DISALLOWED_NC_LICENSE_FOUND:
        {
            return hapi_make_atom(env, "hapi_result_disallowed_nc_license_found");
        }

        case HAPI_RESULT_DISALLOWED_NC_ASSET_WITH_C_LICENSE:
        {
            return hapi_make_atom(env, "hapi_result_disallowed_nc_asset_with_c_license");
        }

        case HAPI_RESULT_DISALLOWED_NC_ASSET_WITH_LC_LICENSE:
        {
            return hapi_make_atom(env, "hapi_result_disallowed_nc_asset_with_lc_license");
        }

        case HAPI_RESULT_DISALLOWED_LC_ASSET_WITH_C_LICENSE:
        {
            return hapi_make_atom(env, "hapi_result_disallowed_lc_asset_with_c_license");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_Result from erl to c. */
bool
hapi_get_hapi_result(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_Result* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_result_success */
        case 3713831785:
        {
            *enum_result = HAPI_RESULT_SUCCESS;
            break;
        }

        /* hapi_result_failure */
        case 1037742049:
        {
            *enum_result = HAPI_RESULT_FAILURE;
            break;
        }

        /* hapi_result_already_initialized */
        case 3090473558:
        {
            *enum_result = HAPI_RESULT_ALREADY_INITIALIZED;
            break;
        }

        /* hapi_result_not_initialized */
        case 2669115710:
        {
            *enum_result = HAPI_RESULT_NOT_INITIALIZED;
            break;
        }

        /* hapi_result_cant_loadfile */
        case 2751182470:
        {
            *enum_result = HAPI_RESULT_CANT_LOADFILE;
            break;
        }

        /* hapi_result_parm_set_failed */
        case 1473470013:
        {
            *enum_result = HAPI_RESULT_PARM_SET_FAILED;
            break;
        }

        /* hapi_result_invalid_argument */
        case 2141895781:
        {
            *enum_result = HAPI_RESULT_INVALID_ARGUMENT;
            break;
        }

        /* hapi_result_cant_load_geo */
        case 2907852441:
        {
            *enum_result = HAPI_RESULT_CANT_LOAD_GEO;
            break;
        }

        /* hapi_result_cant_generate_preset */
        case 1960848769:
        {
            *enum_result = HAPI_RESULT_CANT_GENERATE_PRESET;
            break;
        }

        /* hapi_result_cant_load_preset */
        case 2629656986:
        {
            *enum_result = HAPI_RESULT_CANT_LOAD_PRESET;
            break;
        }

        /* hapi_result_asset_def_already_loaded */
        case 1332688439:
        {
            *enum_result = HAPI_RESULT_ASSET_DEF_ALREADY_LOADED;
            break;
        }

        /* hapi_result_no_license_found */
        case 166875043:
        {
            *enum_result = HAPI_RESULT_NO_LICENSE_FOUND;
            break;
        }

        /* hapi_result_disallowed_nc_license_found */
        case 3661265078:
        {
            *enum_result = HAPI_RESULT_DISALLOWED_NC_LICENSE_FOUND;
            break;
        }

        /* hapi_result_disallowed_nc_asset_with_c_license */
        case 2873502490:
        {
            *enum_result = HAPI_RESULT_DISALLOWED_NC_ASSET_WITH_C_LICENSE;
            break;
        }

        /* hapi_result_disallowed_nc_asset_with_lc_license */
        case 3894063770:
        {
            *enum_result = HAPI_RESULT_DISALLOWED_NC_ASSET_WITH_LC_LICENSE;
            break;
        }

        /* hapi_result_disallowed_lc_asset_with_c_license */
        case 2858294338:
        {
            *enum_result = HAPI_RESULT_DISALLOWED_LC_ASSET_WITH_C_LICENSE;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_CurveType from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_curve_type(ErlNifEnv* env, HAPI_CurveType enum_value)
{
    switch(enum_value)
    {
        case HAPI_CURVETYPE_INVALID:
        {
            return hapi_make_atom(env, "hapi_curvetype_invalid");
        }

        case HAPI_CURVETYPE_LINEAR:
        {
            return hapi_make_atom(env, "hapi_curvetype_linear");
        }

        case HAPI_CURVETYPE_NURBS:
        {
            return hapi_make_atom(env, "hapi_curvetype_nurbs");
        }

        case HAPI_CURVETYPE_BEZIER:
        {
            return hapi_make_atom(env, "hapi_curvetype_bezier");
        }

        case HAPI_CURVETYPE_MAX:
        {
            return hapi_make_atom(env, "hapi_curvetype_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_CurveType from erl to c. */
bool
hapi_get_hapi_curve_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_CurveType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_curvetype_invalid */
        case 2202586514:
        {
            *enum_result = HAPI_CURVETYPE_INVALID;
            break;
        }

        /* hapi_curvetype_linear */
        case 2346647114:
        {
            *enum_result = HAPI_CURVETYPE_LINEAR;
            break;
        }

        /* hapi_curvetype_nurbs */
        case 3129521528:
        {
            *enum_result = HAPI_CURVETYPE_NURBS;
            break;
        }

        /* hapi_curvetype_bezier */
        case 2343775189:
        {
            *enum_result = HAPI_CURVETYPE_BEZIER;
            break;
        }

        /* hapi_curvetype_max */
        case 2118035272:
        {
            *enum_result = HAPI_CURVETYPE_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_StatusVerbosity from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_status_verbosity(ErlNifEnv* env, HAPI_StatusVerbosity enum_value)
{
    switch(enum_value)
    {
        case HAPI_STATUSVERBOSITY_0:
        {
            return hapi_make_atom(env, "hapi_statusverbosity_0");
        }

        case HAPI_STATUSVERBOSITY_1:
        {
            return hapi_make_atom(env, "hapi_statusverbosity_1");
        }

        case HAPI_STATUSVERBOSITY_2:
        {
            return hapi_make_atom(env, "hapi_statusverbosity_2");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_StatusVerbosity from erl to c. */
bool
hapi_get_hapi_status_verbosity(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_StatusVerbosity* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_statusverbosity_0 */
        case 1281355693:
        {
            *enum_result = HAPI_STATUSVERBOSITY_0;
            break;
        }

        /* hapi_statusverbosity_1 */
        case 3580236127:
        {
            *enum_result = HAPI_STATUSVERBOSITY_1;
            break;
        }

        /* hapi_statusverbosity_2 */
        case 2340815382:
        {
            *enum_result = HAPI_STATUSVERBOSITY_2;
            break;
        }

        /* hapi_statusverbosity_all */
        case 342427634:
        {
            *enum_result = HAPI_STATUSVERBOSITY_ALL;
            break;
        }

        /* hapi_statusverbosity_errors */
        case 3898403122:
        {
            *enum_result = HAPI_STATUSVERBOSITY_ERRORS;
            break;
        }

        /* hapi_statusverbosity_warnings */
        case 823904373:
        {
            *enum_result = HAPI_STATUSVERBOSITY_WARNINGS;
            break;
        }

        /* hapi_statusverbosity_messages */
        case 753691706:
        {
            *enum_result = HAPI_STATUSVERBOSITY_MESSAGES;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_Permissions from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_permissions(ErlNifEnv* env, HAPI_Permissions enum_value)
{
    switch(enum_value)
    {
        case HAPI_PERMISSIONS_NON_APPLICABLE:
        {
            return hapi_make_atom(env, "hapi_permissions_non_applicable");
        }

        case HAPI_PERMISSIONS_READ_WRITE:
        {
            return hapi_make_atom(env, "hapi_permissions_read_write");
        }

        case HAPI_PERMISSIONS_READ_ONLY:
        {
            return hapi_make_atom(env, "hapi_permissions_read_only");
        }

        case HAPI_PERMISSIONS_WRITE_ONLY:
        {
            return hapi_make_atom(env, "hapi_permissions_write_only");
        }

        case HAPI_PERMISSIONS_MAX:
        {
            return hapi_make_atom(env, "hapi_permissions_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_Permissions from erl to c. */
bool
hapi_get_hapi_permissions(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_Permissions* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_permissions_non_applicable */
        case 2395404179:
        {
            *enum_result = HAPI_PERMISSIONS_NON_APPLICABLE;
            break;
        }

        /* hapi_permissions_read_write */
        case 3046338534:
        {
            *enum_result = HAPI_PERMISSIONS_READ_WRITE;
            break;
        }

        /* hapi_permissions_read_only */
        case 3590233932:
        {
            *enum_result = HAPI_PERMISSIONS_READ_ONLY;
            break;
        }

        /* hapi_permissions_write_only */
        case 256108734:
        {
            *enum_result = HAPI_PERMISSIONS_WRITE_ONLY;
            break;
        }

        /* hapi_permissions_max */
        case 3126986835:
        {
            *enum_result = HAPI_PERMISSIONS_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_EnvIntType from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_env_int_type(ErlNifEnv* env, HAPI_EnvIntType enum_value)
{
    switch(enum_value)
    {
        case HAPI_ENVINT_INVALID:
        {
            return hapi_make_atom(env, "hapi_envint_invalid");
        }

        case HAPI_ENVINT_VERSION_HOUDINI_MAJOR:
        {
            return hapi_make_atom(env, "hapi_envint_version_houdini_major");
        }

        case HAPI_ENVINT_VERSION_HOUDINI_MINOR:
        {
            return hapi_make_atom(env, "hapi_envint_version_houdini_minor");
        }

        case HAPI_ENVINT_VERSION_HOUDINI_BUILD:
        {
            return hapi_make_atom(env, "hapi_envint_version_houdini_build");
        }

        case HAPI_ENVINT_VERSION_HOUDINI_PATCH:
        {
            return hapi_make_atom(env, "hapi_envint_version_houdini_patch");
        }

        case HAPI_ENVINT_VERSION_ORIG_HOUDINI_MAJOR:
        {
            return hapi_make_atom(env, "hapi_envint_version_orig_houdini_major");
        }

        case HAPI_ENVINT_VERSION_ORIG_HOUDINI_MINOR:
        {
            return hapi_make_atom(env, "hapi_envint_version_orig_houdini_minor");
        }

        case HAPI_ENVINT_VERSION_ORIG_HOUDINI_BUILD:
        {
            return hapi_make_atom(env, "hapi_envint_version_orig_houdini_build");
        }

        case HAPI_ENVINT_VERSION_ORIG_HOUDINI_PATCH:
        {
            return hapi_make_atom(env, "hapi_envint_version_orig_houdini_patch");
        }

        case HAPI_ENVINT_VERSION_HOUDINI_ENGINE_MAJOR:
        {
            return hapi_make_atom(env, "hapi_envint_version_houdini_engine_major");
        }

        case HAPI_ENVINT_VERSION_HOUDINI_ENGINE_MINOR:
        {
            return hapi_make_atom(env, "hapi_envint_version_houdini_engine_minor");
        }

        case HAPI_ENVINT_VERSION_HOUDINI_ENGINE_API:
        {
            return hapi_make_atom(env, "hapi_envint_version_houdini_engine_api");
        }

        case HAPI_ENVINT_LICENSE:
        {
            return hapi_make_atom(env, "hapi_envint_license");
        }

        case HAPI_ENVINT_MAX:
        {
            return hapi_make_atom(env, "hapi_envint_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_EnvIntType from erl to c. */
bool
hapi_get_hapi_env_int_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_EnvIntType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_envint_invalid */
        case 3841512571:
        {
            *enum_result = HAPI_ENVINT_INVALID;
            break;
        }

        /* hapi_envint_version_houdini_major */
        case 729783216:
        {
            *enum_result = HAPI_ENVINT_VERSION_HOUDINI_MAJOR;
            break;
        }

        /* hapi_envint_version_houdini_minor */
        case 2183966821:
        {
            *enum_result = HAPI_ENVINT_VERSION_HOUDINI_MINOR;
            break;
        }

        /* hapi_envint_version_houdini_build */
        case 2359290413:
        {
            *enum_result = HAPI_ENVINT_VERSION_HOUDINI_BUILD;
            break;
        }

        /* hapi_envint_version_houdini_patch */
        case 2304600462:
        {
            *enum_result = HAPI_ENVINT_VERSION_HOUDINI_PATCH;
            break;
        }

        /* hapi_envint_version_orig_houdini_major */
        case 3489108176:
        {
            *enum_result = HAPI_ENVINT_VERSION_ORIG_HOUDINI_MAJOR;
            break;
        }

        /* hapi_envint_version_orig_houdini_minor */
        case 4098809334:
        {
            *enum_result = HAPI_ENVINT_VERSION_ORIG_HOUDINI_MINOR;
            break;
        }

        /* hapi_envint_version_orig_houdini_build */
        case 370554041:
        {
            *enum_result = HAPI_ENVINT_VERSION_ORIG_HOUDINI_BUILD;
            break;
        }

        /* hapi_envint_version_orig_houdini_patch */
        case 1477480701:
        {
            *enum_result = HAPI_ENVINT_VERSION_ORIG_HOUDINI_PATCH;
            break;
        }

        /* hapi_envint_version_houdini_engine_major */
        case 2437871873:
        {
            *enum_result = HAPI_ENVINT_VERSION_HOUDINI_ENGINE_MAJOR;
            break;
        }

        /* hapi_envint_version_houdini_engine_minor */
        case 3017839496:
        {
            *enum_result = HAPI_ENVINT_VERSION_HOUDINI_ENGINE_MINOR;
            break;
        }

        /* hapi_envint_version_houdini_engine_api */
        case 2017899821:
        {
            *enum_result = HAPI_ENVINT_VERSION_HOUDINI_ENGINE_API;
            break;
        }

        /* hapi_envint_license */
        case 4199554980:
        {
            *enum_result = HAPI_ENVINT_LICENSE;
            break;
        }

        /* hapi_envint_max */
        case 34438215:
        {
            *enum_result = HAPI_ENVINT_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_AssetSubType from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_asset_sub_type(ErlNifEnv* env, HAPI_AssetSubType enum_value)
{
    switch(enum_value)
    {
        case HAPI_ASSETSUBTYPE_INVALID:
        {
            return hapi_make_atom(env, "hapi_assetsubtype_invalid");
        }

        case HAPI_ASSETSUBTYPE_DEFAULT:
        {
            return hapi_make_atom(env, "hapi_assetsubtype_default");
        }

        case HAPI_ASSETSUBTYPE_CURVE:
        {
            return hapi_make_atom(env, "hapi_assetsubtype_curve");
        }

        case HAPI_ASSETSUBTYPE_INPUT:
        {
            return hapi_make_atom(env, "hapi_assetsubtype_input");
        }

        case HAPI_ASSETSUBTYPE_MAX:
        {
            return hapi_make_atom(env, "hapi_assetsubtype_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_AssetSubType from erl to c. */
bool
hapi_get_hapi_asset_sub_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_AssetSubType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_assetsubtype_invalid */
        case 4274947295:
        {
            *enum_result = HAPI_ASSETSUBTYPE_INVALID;
            break;
        }

        /* hapi_assetsubtype_default */
        case 3111968334:
        {
            *enum_result = HAPI_ASSETSUBTYPE_DEFAULT;
            break;
        }

        /* hapi_assetsubtype_curve */
        case 920954547:
        {
            *enum_result = HAPI_ASSETSUBTYPE_CURVE;
            break;
        }

        /* hapi_assetsubtype_input */
        case 3978905612:
        {
            *enum_result = HAPI_ASSETSUBTYPE_INPUT;
            break;
        }

        /* hapi_assetsubtype_max */
        case 1492763276:
        {
            *enum_result = HAPI_ASSETSUBTYPE_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_GroupType from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_group_type(ErlNifEnv* env, HAPI_GroupType enum_value)
{
    switch(enum_value)
    {
        case HAPI_GROUPTYPE_INVALID:
        {
            return hapi_make_atom(env, "hapi_grouptype_invalid");
        }

        case HAPI_GROUPTYPE_POINT:
        {
            return hapi_make_atom(env, "hapi_grouptype_point");
        }

        case HAPI_GROUPTYPE_PRIM:
        {
            return hapi_make_atom(env, "hapi_grouptype_prim");
        }

        case HAPI_GROUPTYPE_MAX:
        {
            return hapi_make_atom(env, "hapi_grouptype_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_GroupType from erl to c. */
bool
hapi_get_hapi_group_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_GroupType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_grouptype_invalid */
        case 1807777027:
        {
            *enum_result = HAPI_GROUPTYPE_INVALID;
            break;
        }

        /* hapi_grouptype_point */
        case 3354691949:
        {
            *enum_result = HAPI_GROUPTYPE_POINT;
            break;
        }

        /* hapi_grouptype_prim */
        case 2860112191:
        {
            *enum_result = HAPI_GROUPTYPE_PRIM;
            break;
        }

        /* hapi_grouptype_max */
        case 2983497873:
        {
            *enum_result = HAPI_GROUPTYPE_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_TransformComponent from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_transform_component(ErlNifEnv* env, HAPI_TransformComponent enum_value)
{
    switch(enum_value)
    {
        case HAPI_TRANSFORM_TX:
        {
            return hapi_make_atom(env, "hapi_transform_tx");
        }

        case HAPI_TRANSFORM_TY:
        {
            return hapi_make_atom(env, "hapi_transform_ty");
        }

        case HAPI_TRANSFORM_TZ:
        {
            return hapi_make_atom(env, "hapi_transform_tz");
        }

        case HAPI_TRANSFORM_RX:
        {
            return hapi_make_atom(env, "hapi_transform_rx");
        }

        case HAPI_TRANSFORM_RY:
        {
            return hapi_make_atom(env, "hapi_transform_ry");
        }

        case HAPI_TRANSFORM_RZ:
        {
            return hapi_make_atom(env, "hapi_transform_rz");
        }

        case HAPI_TRANSFORM_QX:
        {
            return hapi_make_atom(env, "hapi_transform_qx");
        }

        case HAPI_TRANSFORM_QY:
        {
            return hapi_make_atom(env, "hapi_transform_qy");
        }

        case HAPI_TRANSFORM_QZ:
        {
            return hapi_make_atom(env, "hapi_transform_qz");
        }

        case HAPI_TRANSFORM_QW:
        {
            return hapi_make_atom(env, "hapi_transform_qw");
        }

        case HAPI_TRANSFORM_SX:
        {
            return hapi_make_atom(env, "hapi_transform_sx");
        }

        case HAPI_TRANSFORM_SY:
        {
            return hapi_make_atom(env, "hapi_transform_sy");
        }

        case HAPI_TRANSFORM_SZ:
        {
            return hapi_make_atom(env, "hapi_transform_sz");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_TransformComponent from erl to c. */
bool
hapi_get_hapi_transform_component(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_TransformComponent* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_transform_tx */
        case 2763045797:
        {
            *enum_result = HAPI_TRANSFORM_TX;
            break;
        }

        /* hapi_transform_ty */
        case 1138742908:
        {
            *enum_result = HAPI_TRANSFORM_TY;
            break;
        }

        /* hapi_transform_tz */
        case 1366188897:
        {
            *enum_result = HAPI_TRANSFORM_TZ;
            break;
        }

        /* hapi_transform_rx */
        case 1796486426:
        {
            *enum_result = HAPI_TRANSFORM_RX;
            break;
        }

        /* hapi_transform_ry */
        case 41409567:
        {
            *enum_result = HAPI_TRANSFORM_RY;
            break;
        }

        /* hapi_transform_rz */
        case 2024189270:
        {
            *enum_result = HAPI_TRANSFORM_RZ;
            break;
        }

        /* hapi_transform_qx */
        case 3784000339:
        {
            *enum_result = HAPI_TRANSFORM_QX;
            break;
        }

        /* hapi_transform_qy */
        case 2697215009:
        {
            *enum_result = HAPI_TRANSFORM_QY;
            break;
        }

        /* hapi_transform_qz */
        case 1869023627:
        {
            *enum_result = HAPI_TRANSFORM_QZ;
            break;
        }

        /* hapi_transform_qw */
        case 1077003245:
        {
            *enum_result = HAPI_TRANSFORM_QW;
            break;
        }

        /* hapi_transform_sx */
        case 3242450707:
        {
            *enum_result = HAPI_TRANSFORM_SX;
            break;
        }

        /* hapi_transform_sy */
        case 2683523763:
        {
            *enum_result = HAPI_TRANSFORM_SY;
            break;
        }

        /* hapi_transform_sz */
        case 1336671716:
        {
            *enum_result = HAPI_TRANSFORM_SZ;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_StatusType from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_status_type(ErlNifEnv* env, HAPI_StatusType enum_value)
{
    switch(enum_value)
    {
        case HAPI_STATUS_CALL_RESULT:
        {
            return hapi_make_atom(env, "hapi_status_call_result");
        }

        case HAPI_STATUS_COOK_RESULT:
        {
            return hapi_make_atom(env, "hapi_status_cook_result");
        }

        case HAPI_STATUS_COOK_STATE:
        {
            return hapi_make_atom(env, "hapi_status_cook_state");
        }

        case HAPI_STATUS_MAX:
        {
            return hapi_make_atom(env, "hapi_status_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_StatusType from erl to c. */
bool
hapi_get_hapi_status_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_StatusType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_status_call_result */
        case 2001185294:
        {
            *enum_result = HAPI_STATUS_CALL_RESULT;
            break;
        }

        /* hapi_status_cook_result */
        case 2030323224:
        {
            *enum_result = HAPI_STATUS_COOK_RESULT;
            break;
        }

        /* hapi_status_cook_state */
        case 3336497966:
        {
            *enum_result = HAPI_STATUS_COOK_STATE;
            break;
        }

        /* hapi_status_max */
        case 220878498:
        {
            *enum_result = HAPI_STATUS_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_State from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_state(ErlNifEnv* env, HAPI_State enum_value)
{
    switch(enum_value)
    {
        case HAPI_STATE_READY:
        {
            return hapi_make_atom(env, "hapi_state_ready");
        }

        case HAPI_STATE_READY_WITH_FATAL_ERRORS:
        {
            return hapi_make_atom(env, "hapi_state_ready_with_fatal_errors");
        }

        case HAPI_STATE_READY_WITH_COOK_ERRORS:
        {
            return hapi_make_atom(env, "hapi_state_ready_with_cook_errors");
        }

        case HAPI_STATE_STARTING_COOK:
        {
            return hapi_make_atom(env, "hapi_state_starting_cook");
        }

        case HAPI_STATE_COOKING:
        {
            return hapi_make_atom(env, "hapi_state_cooking");
        }

        case HAPI_STATE_STARTING_LOAD:
        {
            return hapi_make_atom(env, "hapi_state_starting_load");
        }

        case HAPI_STATE_LOADING:
        {
            return hapi_make_atom(env, "hapi_state_loading");
        }

        case HAPI_STATE_MAX:
        {
            return hapi_make_atom(env, "hapi_state_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_State from erl to c. */
bool
hapi_get_hapi_state(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_State* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_state_ready */
        case 3648387321:
        {
            *enum_result = HAPI_STATE_READY;
            break;
        }

        /* hapi_state_ready_with_fatal_errors */
        case 2824922871:
        {
            *enum_result = HAPI_STATE_READY_WITH_FATAL_ERRORS;
            break;
        }

        /* hapi_state_ready_with_cook_errors */
        case 2342148041:
        {
            *enum_result = HAPI_STATE_READY_WITH_COOK_ERRORS;
            break;
        }

        /* hapi_state_starting_cook */
        case 2553053177:
        {
            *enum_result = HAPI_STATE_STARTING_COOK;
            break;
        }

        /* hapi_state_cooking */
        case 3690862542:
        {
            *enum_result = HAPI_STATE_COOKING;
            break;
        }

        /* hapi_state_starting_load */
        case 3620837358:
        {
            *enum_result = HAPI_STATE_STARTING_LOAD;
            break;
        }

        /* hapi_state_loading */
        case 849338667:
        {
            *enum_result = HAPI_STATE_LOADING;
            break;
        }

        /* hapi_state_max */
        case 3467810446:
        {
            *enum_result = HAPI_STATE_MAX;
            break;
        }

        /* hapi_state_max_ready_state */
        case 35607980:
        {
            *enum_result = HAPI_STATE_MAX_READY_STATE;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_CurveOrders from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_curve_orders(ErlNifEnv* env, HAPI_CurveOrders enum_value)
{
    switch(enum_value)
    {
        case HAPI_CURVE_ORDER_VARYING:
        {
            return hapi_make_atom(env, "hapi_curve_order_varying");
        }

        case HAPI_CURVE_ORDER_INVALID:
        {
            return hapi_make_atom(env, "hapi_curve_order_invalid");
        }

        case HAPI_CURVE_ORDER_LINEAR:
        {
            return hapi_make_atom(env, "hapi_curve_order_linear");
        }

        case HAPI_CURVE_ORDER_QUADRATIC:
        {
            return hapi_make_atom(env, "hapi_curve_order_quadratic");
        }

        case HAPI_CURVE_ORDER_CUBIC:
        {
            return hapi_make_atom(env, "hapi_curve_order_cubic");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_CurveOrders from erl to c. */
bool
hapi_get_hapi_curve_orders(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_CurveOrders* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_curve_order_varying */
        case 1332844792:
        {
            *enum_result = HAPI_CURVE_ORDER_VARYING;
            break;
        }

        /* hapi_curve_order_invalid */
        case 3692858437:
        {
            *enum_result = HAPI_CURVE_ORDER_INVALID;
            break;
        }

        /* hapi_curve_order_linear */
        case 1573102780:
        {
            *enum_result = HAPI_CURVE_ORDER_LINEAR;
            break;
        }

        /* hapi_curve_order_quadratic */
        case 3031663613:
        {
            *enum_result = HAPI_CURVE_ORDER_QUADRATIC;
            break;
        }

        /* hapi_curve_order_cubic */
        case 4027595125:
        {
            *enum_result = HAPI_CURVE_ORDER_CUBIC;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_PresetType from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_preset_type(ErlNifEnv* env, HAPI_PresetType enum_value)
{
    switch(enum_value)
    {
        case HAPI_PRESETTYPE_INVALID:
        {
            return hapi_make_atom(env, "hapi_presettype_invalid");
        }

        case HAPI_PRESETTYPE_BINARY:
        {
            return hapi_make_atom(env, "hapi_presettype_binary");
        }

        case HAPI_PRESETTYPE_IDX:
        {
            return hapi_make_atom(env, "hapi_presettype_idx");
        }

        case HAPI_PRESETTYPE_MAX:
        {
            return hapi_make_atom(env, "hapi_presettype_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_PresetType from erl to c. */
bool
hapi_get_hapi_preset_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_PresetType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_presettype_invalid */
        case 3370572381:
        {
            *enum_result = HAPI_PRESETTYPE_INVALID;
            break;
        }

        /* hapi_presettype_binary */
        case 1629204808:
        {
            *enum_result = HAPI_PRESETTYPE_BINARY;
            break;
        }

        /* hapi_presettype_idx */
        case 2476503831:
        {
            *enum_result = HAPI_PRESETTYPE_IDX;
            break;
        }

        /* hapi_presettype_max */
        case 1183497328:
        {
            *enum_result = HAPI_PRESETTYPE_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_ParmType from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_parm_type(ErlNifEnv* env, HAPI_ParmType enum_value)
{
    switch(enum_value)
    {
        case HAPI_PARMTYPE_INT:
        {
            return hapi_make_atom(env, "hapi_parmtype_int");
        }

        case HAPI_PARMTYPE_MULTIPARMLIST:
        {
            return hapi_make_atom(env, "hapi_parmtype_multiparmlist");
        }

        case HAPI_PARMTYPE_TOGGLE:
        {
            return hapi_make_atom(env, "hapi_parmtype_toggle");
        }

        case HAPI_PARMTYPE_BUTTON:
        {
            return hapi_make_atom(env, "hapi_parmtype_button");
        }

        case HAPI_PARMTYPE_FLOAT:
        {
            return hapi_make_atom(env, "hapi_parmtype_float");
        }

        case HAPI_PARMTYPE_COLOR:
        {
            return hapi_make_atom(env, "hapi_parmtype_color");
        }

        case HAPI_PARMTYPE_STRING:
        {
            return hapi_make_atom(env, "hapi_parmtype_string");
        }

        case HAPI_PARMTYPE_PATH_FILE:
        {
            return hapi_make_atom(env, "hapi_parmtype_path_file");
        }

        case HAPI_PARMTYPE_PATH_FILE_GEO:
        {
            return hapi_make_atom(env, "hapi_parmtype_path_file_geo");
        }

        case HAPI_PARMTYPE_PATH_FILE_IMAGE:
        {
            return hapi_make_atom(env, "hapi_parmtype_path_file_image");
        }

        case HAPI_PARMTYPE_PATH_NODE:
        {
            return hapi_make_atom(env, "hapi_parmtype_path_node");
        }

        case HAPI_PARMTYPE_FOLDERLIST:
        {
            return hapi_make_atom(env, "hapi_parmtype_folderlist");
        }

        case HAPI_PARMTYPE_FOLDER:
        {
            return hapi_make_atom(env, "hapi_parmtype_folder");
        }

        case HAPI_PARMTYPE_LABEL:
        {
            return hapi_make_atom(env, "hapi_parmtype_label");
        }

        case HAPI_PARMTYPE_SEPARATOR:
        {
            return hapi_make_atom(env, "hapi_parmtype_separator");
        }

        case HAPI_PARMTYPE_MAX:
        {
            return hapi_make_atom(env, "hapi_parmtype_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_ParmType from erl to c. */
bool
hapi_get_hapi_parm_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ParmType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_parmtype_int */
        case 2938205493:
        {
            *enum_result = HAPI_PARMTYPE_INT;
            break;
        }

        /* hapi_parmtype_multiparmlist */
        case 94525824:
        {
            *enum_result = HAPI_PARMTYPE_MULTIPARMLIST;
            break;
        }

        /* hapi_parmtype_toggle */
        case 3487126731:
        {
            *enum_result = HAPI_PARMTYPE_TOGGLE;
            break;
        }

        /* hapi_parmtype_button */
        case 3222095719:
        {
            *enum_result = HAPI_PARMTYPE_BUTTON;
            break;
        }

        /* hapi_parmtype_float */
        case 3403782401:
        {
            *enum_result = HAPI_PARMTYPE_FLOAT;
            break;
        }

        /* hapi_parmtype_color */
        case 3651575535:
        {
            *enum_result = HAPI_PARMTYPE_COLOR;
            break;
        }

        /* hapi_parmtype_string */
        case 3029524656:
        {
            *enum_result = HAPI_PARMTYPE_STRING;
            break;
        }

        /* hapi_parmtype_path_file */
        case 3946815810:
        {
            *enum_result = HAPI_PARMTYPE_PATH_FILE;
            break;
        }

        /* hapi_parmtype_path_file_geo */
        case 2237470241:
        {
            *enum_result = HAPI_PARMTYPE_PATH_FILE_GEO;
            break;
        }

        /* hapi_parmtype_path_file_image */
        case 3582069620:
        {
            *enum_result = HAPI_PARMTYPE_PATH_FILE_IMAGE;
            break;
        }

        /* hapi_parmtype_path_node */
        case 1563877995:
        {
            *enum_result = HAPI_PARMTYPE_PATH_NODE;
            break;
        }

        /* hapi_parmtype_folderlist */
        case 465413589:
        {
            *enum_result = HAPI_PARMTYPE_FOLDERLIST;
            break;
        }

        /* hapi_parmtype_folder */
        case 1692078012:
        {
            *enum_result = HAPI_PARMTYPE_FOLDER;
            break;
        }

        /* hapi_parmtype_label */
        case 4255272841:
        {
            *enum_result = HAPI_PARMTYPE_LABEL;
            break;
        }

        /* hapi_parmtype_separator */
        case 2360826373:
        {
            *enum_result = HAPI_PARMTYPE_SEPARATOR;
            break;
        }

        /* hapi_parmtype_max */
        case 220098758:
        {
            *enum_result = HAPI_PARMTYPE_MAX;
            break;
        }

        /* hapi_parmtype_int_start */
        case 2793337556:
        {
            *enum_result = HAPI_PARMTYPE_INT_START;
            break;
        }

        /* hapi_parmtype_int_end */
        case 2924084007:
        {
            *enum_result = HAPI_PARMTYPE_INT_END;
            break;
        }

        /* hapi_parmtype_float_start */
        case 3597937322:
        {
            *enum_result = HAPI_PARMTYPE_FLOAT_START;
            break;
        }

        /* hapi_parmtype_float_end */
        case 2584819633:
        {
            *enum_result = HAPI_PARMTYPE_FLOAT_END;
            break;
        }

        /* hapi_parmtype_string_start */
        case 2299523298:
        {
            *enum_result = HAPI_PARMTYPE_STRING_START;
            break;
        }

        /* hapi_parmtype_string_end */
        case 883769106:
        {
            *enum_result = HAPI_PARMTYPE_STRING_END;
            break;
        }

        /* hapi_parmtype_path_start */
        case 1937567703:
        {
            *enum_result = HAPI_PARMTYPE_PATH_START;
            break;
        }

        /* hapi_parmtype_path_end */
        case 233945276:
        {
            *enum_result = HAPI_PARMTYPE_PATH_END;
            break;
        }

        /* hapi_parmtype_path_file_start */
        case 2795114217:
        {
            *enum_result = HAPI_PARMTYPE_PATH_FILE_START;
            break;
        }

        /* hapi_parmtype_path_file_end */
        case 4055995372:
        {
            *enum_result = HAPI_PARMTYPE_PATH_FILE_END;
            break;
        }

        /* hapi_parmtype_path_node_start */
        case 3219598411:
        {
            *enum_result = HAPI_PARMTYPE_PATH_NODE_START;
            break;
        }

        /* hapi_parmtype_path_node_end */
        case 381338848:
        {
            *enum_result = HAPI_PARMTYPE_PATH_NODE_END;
            break;
        }

        /* hapi_parmtype_container_start */
        case 1309661876:
        {
            *enum_result = HAPI_PARMTYPE_CONTAINER_START;
            break;
        }

        /* hapi_parmtype_container_end */
        case 2873311351:
        {
            *enum_result = HAPI_PARMTYPE_CONTAINER_END;
            break;
        }

        /* hapi_parmtype_nonvalue_start */
        case 1808937396:
        {
            *enum_result = HAPI_PARMTYPE_NONVALUE_START;
            break;
        }

        /* hapi_parmtype_nonvalue_end */
        case 920931063:
        {
            *enum_result = HAPI_PARMTYPE_NONVALUE_END;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


/* Converting HAPI_StorageType from c to erl. */
ERL_NIF_TERM
hapi_make_hapi_storage_type(ErlNifEnv* env, HAPI_StorageType enum_value)
{
    switch(enum_value)
    {
        case HAPI_STORAGETYPE_INVALID:
        {
            return hapi_make_atom(env, "hapi_storagetype_invalid");
        }

        case HAPI_STORAGETYPE_INT:
        {
            return hapi_make_atom(env, "hapi_storagetype_int");
        }

        case HAPI_STORAGETYPE_FLOAT:
        {
            return hapi_make_atom(env, "hapi_storagetype_float");
        }

        case HAPI_STORAGETYPE_STRING:
        {
            return hapi_make_atom(env, "hapi_storagetype_string");
        }

        case HAPI_STORAGETYPE_MAX:
        {
            return hapi_make_atom(env, "hapi_storagetype_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


/* Converting HAPI_StorageType from erl to c. */
bool
hapi_get_hapi_storage_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_StorageType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_storagetype_invalid */
        case 2592088464:
        {
            *enum_result = HAPI_STORAGETYPE_INVALID;
            break;
        }

        /* hapi_storagetype_int */
        case 2403500183:
        {
            *enum_result = HAPI_STORAGETYPE_INT;
            break;
        }

        /* hapi_storagetype_float */
        case 604801786:
        {
            *enum_result = HAPI_STORAGETYPE_FLOAT;
            break;
        }

        /* hapi_storagetype_string */
        case 3554866194:
        {
            *enum_result = HAPI_STORAGETYPE_STRING;
            break;
        }

        /* hapi_storagetype_max */
        case 1435904941:
        {
            *enum_result = HAPI_STORAGETYPE_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}

