/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_types_nif.c.template

#include "hapi_private_nif.h"
#include "hapi_types_nif.h"


/* Converting HAPI_ObjectId from c to erl. */
ERL_NIF_TERM
hapi_priv_make_hapi_object_id(ErlNifEnv* env, HAPI_ObjectId hapi_type)
{
    return hapi_priv_make_int(env, (int) hapi_type);
}


/* Converting HAPI_ObjectId from erl to c. */
bool
hapi_priv_get_hapi_object_id(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ObjectId* hapi_type)
{
    return hapi_priv_get_int(env, term, (int*) hapi_type);
}


/* Converting HAPI_ParmId from c to erl. */
ERL_NIF_TERM
hapi_priv_make_hapi_parm_id(ErlNifEnv* env, HAPI_ParmId hapi_type)
{
    return hapi_priv_make_int(env, (int) hapi_type);
}


/* Converting HAPI_ParmId from erl to c. */
bool
hapi_priv_get_hapi_parm_id(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ParmId* hapi_type)
{
    return hapi_priv_get_int(env, term, (int*) hapi_type);
}


/* Converting HAPI_AssetLibraryId from c to erl. */
ERL_NIF_TERM
hapi_priv_make_hapi_asset_library_id(ErlNifEnv* env, HAPI_AssetLibraryId hapi_type)
{
    return hapi_priv_make_int(env, (int) hapi_type);
}


/* Converting HAPI_AssetLibraryId from erl to c. */
bool
hapi_priv_get_hapi_asset_library_id(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_AssetLibraryId* hapi_type)
{
    return hapi_priv_get_int(env, term, (int*) hapi_type);
}


/* Converting HAPI_Bool from c to erl. */
ERL_NIF_TERM
hapi_priv_make_hapi_bool(ErlNifEnv* env, HAPI_Bool hapi_type)
{
    return hapi_priv_make_bool(env, (bool) hapi_type);
}


/* Converting HAPI_Bool from erl to c. */
bool
hapi_priv_get_hapi_bool(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_Bool* hapi_type)
{
    return hapi_priv_get_bool(env, term, (bool*) hapi_type);
}


/* Converting HAPI_NodeId from c to erl. */
ERL_NIF_TERM
hapi_priv_make_hapi_node_id(ErlNifEnv* env, HAPI_NodeId hapi_type)
{
    return hapi_priv_make_int(env, (int) hapi_type);
}


/* Converting HAPI_NodeId from erl to c. */
bool
hapi_priv_get_hapi_node_id(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_NodeId* hapi_type)
{
    return hapi_priv_get_int(env, term, (int*) hapi_type);
}


/* Converting HAPI_GeoId from c to erl. */
ERL_NIF_TERM
hapi_priv_make_hapi_geo_id(ErlNifEnv* env, HAPI_GeoId hapi_type)
{
    return hapi_priv_make_int(env, (int) hapi_type);
}


/* Converting HAPI_GeoId from erl to c. */
bool
hapi_priv_get_hapi_geo_id(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_GeoId* hapi_type)
{
    return hapi_priv_get_int(env, term, (int*) hapi_type);
}


/* Converting HAPI_StringHandle from c to erl. */
ERL_NIF_TERM
hapi_priv_make_hapi_string_handle(ErlNifEnv* env, HAPI_StringHandle hapi_type)
{
    return hapi_priv_make_int(env, (int) hapi_type);
}


/* Converting HAPI_StringHandle from erl to c. */
bool
hapi_priv_get_hapi_string_handle(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_StringHandle* hapi_type)
{
    return hapi_priv_get_int(env, term, (int*) hapi_type);
}


/* Converting HAPI_AssetId from c to erl. */
ERL_NIF_TERM
hapi_priv_make_hapi_asset_id(ErlNifEnv* env, HAPI_AssetId hapi_type)
{
    return hapi_priv_make_int(env, (int) hapi_type);
}


/* Converting HAPI_AssetId from erl to c. */
bool
hapi_priv_get_hapi_asset_id(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_AssetId* hapi_type)
{
    return hapi_priv_get_int(env, term, (int*) hapi_type);
}


/* Converting HAPI_PartId from c to erl. */
ERL_NIF_TERM
hapi_priv_make_hapi_part_id(ErlNifEnv* env, HAPI_PartId hapi_type)
{
    return hapi_priv_make_int(env, (int) hapi_type);
}


/* Converting HAPI_PartId from erl to c. */
bool
hapi_priv_get_hapi_part_id(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_PartId* hapi_type)
{
    return hapi_priv_get_int(env, term, (int*) hapi_type);
}


/* Converting HAPI_MaterialId from c to erl. */
ERL_NIF_TERM
hapi_priv_make_hapi_material_id(ErlNifEnv* env, HAPI_MaterialId hapi_type)
{
    return hapi_priv_make_int(env, (int) hapi_type);
}


/* Converting HAPI_MaterialId from erl to c. */
bool
hapi_priv_get_hapi_material_id(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_MaterialId* hapi_type)
{
    return hapi_priv_get_int(env, term, (int*) hapi_type);
}

