/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_StorageType enum from HAPI_Common.h

#include "../hapi_private_nif.h"
#include <string.h>


bool
hapi_storagetype_erl_to_c(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_StorageType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_storagetype_invalid */
        case 2592088464:
        {
            *enum_result = HAPI_STORAGETYPE_INVALID;
            break;
        }

        /* hapi_storagetype_int */
        case 2403500183:
        {
            *enum_result = HAPI_STORAGETYPE_INT;
            break;
        }

        /* hapi_storagetype_float */
        case 604801786:
        {
            *enum_result = HAPI_STORAGETYPE_FLOAT;
            break;
        }

        /* hapi_storagetype_string */
        case 3554866194:
        {
            *enum_result = HAPI_STORAGETYPE_STRING;
            break;
        }

        /* hapi_storagetype_max */
        case 1435904941:
        {
            *enum_result = HAPI_STORAGETYPE_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


ERL_NIF_TERM
hapi_storagetype_c_to_erl(ErlNifEnv* env, HAPI_StorageType enum_value)
{
    switch(enum_value)
    {
        case HAPI_STORAGETYPE_INVALID:
        {
            return hapi_make_atom(env, "hapi_storagetype_invalid");
        }

        case HAPI_STORAGETYPE_INT:
        {
            return hapi_make_atom(env, "hapi_storagetype_int");
        }

        case HAPI_STORAGETYPE_FLOAT:
        {
            return hapi_make_atom(env, "hapi_storagetype_float");
        }

        case HAPI_STORAGETYPE_STRING:
        {
            return hapi_make_atom(env, "hapi_storagetype_string");
        }

        case HAPI_STORAGETYPE_MAX:
        {
            return hapi_make_atom(env, "hapi_storagetype_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}
