/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_XYZOrder enum from HAPI_Common.h

#include "../hapi_private_nif.h"
#include <string.h>


ERL_NIF_TERM
hapi_make_hapi_xyzorder(ErlNifEnv* env, HAPI_XYZOrder enum_value)
{
    switch(enum_value)
    {
        case HAPI_XYZ:
        {
            return hapi_make_atom(env, "hapi_xyz");
        }

        case HAPI_XZY:
        {
            return hapi_make_atom(env, "hapi_xzy");
        }

        case HAPI_YXZ:
        {
            return hapi_make_atom(env, "hapi_yxz");
        }

        case HAPI_YZX:
        {
            return hapi_make_atom(env, "hapi_yzx");
        }

        case HAPI_ZXY:
        {
            return hapi_make_atom(env, "hapi_zxy");
        }

        case HAPI_ZYX:
        {
            return hapi_make_atom(env, "hapi_zyx");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}


bool
hapi_get_hapi_xyzorder(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_XYZOrder* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_xyz */
        case 2568995979:
        {
            *enum_result = HAPI_XYZ;
            break;
        }

        /* hapi_xzy */
        case 3456057817:
        {
            *enum_result = HAPI_XZY;
            break;
        }

        /* hapi_yxz */
        case 535519317:
        {
            *enum_result = HAPI_YXZ;
            break;
        }

        /* hapi_yzx */
        case 2498703819:
        {
            *enum_result = HAPI_YZX;
            break;
        }

        /* hapi_zxy */
        case 4080643183:
        {
            *enum_result = HAPI_ZXY;
            break;
        }

        /* hapi_zyx */
        case 2804301731:
        {
            *enum_result = HAPI_ZYX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}
