/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_ImagePacking enum from HAPI_Common.h

#include "../hapi_private_nif.h"
#include <string.h>


bool
hapi_imagepacking_erl_to_c(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ImagePacking* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_image_packing_unknown */
        case 1026533579:
        {
            *enum_result = HAPI_IMAGE_PACKING_UNKNOWN;
            break;
        }

        /* hapi_image_packing_single */
        case 4027772177:
        {
            *enum_result = HAPI_IMAGE_PACKING_SINGLE;
            break;
        }

        /* hapi_image_packing_dual */
        case 3618580164:
        {
            *enum_result = HAPI_IMAGE_PACKING_DUAL;
            break;
        }

        /* hapi_image_packing_rgb */
        case 1954788252:
        {
            *enum_result = HAPI_IMAGE_PACKING_RGB;
            break;
        }

        /* hapi_image_packing_bgr */
        case 3355295031:
        {
            *enum_result = HAPI_IMAGE_PACKING_BGR;
            break;
        }

        /* hapi_image_packing_rgba */
        case 211676614:
        {
            *enum_result = HAPI_IMAGE_PACKING_RGBA;
            break;
        }

        /* hapi_image_packing_abgr */
        case 4154788832:
        {
            *enum_result = HAPI_IMAGE_PACKING_ABGR;
            break;
        }

        /* hapi_image_packing_max */
        case 2046891834:
        {
            *enum_result = HAPI_IMAGE_PACKING_MAX;
            break;
        }

        /* hapi_image_packing_default3 */
        case 3652598404:
        {
            *enum_result = HAPI_IMAGE_PACKING_DEFAULT3;
            break;
        }

        /* hapi_image_packing_default4 */
        case 1347420588:
        {
            *enum_result = HAPI_IMAGE_PACKING_DEFAULT4;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


ERL_NIF_TERM
hapi_imagepacking_c_to_erl(ErlNifEnv* env, HAPI_ImagePacking enum_value)
{
    switch(enum_value)
    {
        case HAPI_IMAGE_PACKING_UNKNOWN:
        {
            return hapi_make_atom(env, "hapi_image_packing_unknown");
        }

        case HAPI_IMAGE_PACKING_SINGLE:
        {
            return hapi_make_atom(env, "hapi_image_packing_single");
        }

        case HAPI_IMAGE_PACKING_DUAL:
        {
            return hapi_make_atom(env, "hapi_image_packing_dual");
        }

        case HAPI_IMAGE_PACKING_RGB:
        {
            return hapi_make_atom(env, "hapi_image_packing_rgb");
        }

        case HAPI_IMAGE_PACKING_BGR:
        {
            return hapi_make_atom(env, "hapi_image_packing_bgr");
        }

        case HAPI_IMAGE_PACKING_RGBA:
        {
            return hapi_make_atom(env, "hapi_image_packing_rgba");
        }

        case HAPI_IMAGE_PACKING_ABGR:
        {
            return hapi_make_atom(env, "hapi_image_packing_abgr");
        }

        case HAPI_IMAGE_PACKING_MAX:
        {
            return hapi_make_atom(env, "hapi_image_packing_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}
