/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_AttributeOwner enum from HAPI_Common.h

#include "../hapi_private_nif.h"
#include <string.h>


bool
hapi_make_hapi_attributeowner_(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_AttributeOwner* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_attrowner_invalid */
        case 679692306:
        {
            *enum_result = HAPI_ATTROWNER_INVALID;
            break;
        }

        /* hapi_attrowner_vertex */
        case 3318397195:
        {
            *enum_result = HAPI_ATTROWNER_VERTEX;
            break;
        }

        /* hapi_attrowner_point */
        case 902726316:
        {
            *enum_result = HAPI_ATTROWNER_POINT;
            break;
        }

        /* hapi_attrowner_prim */
        case 3208328655:
        {
            *enum_result = HAPI_ATTROWNER_PRIM;
            break;
        }

        /* hapi_attrowner_detail */
        case 1131849991:
        {
            *enum_result = HAPI_ATTROWNER_DETAIL;
            break;
        }

        /* hapi_attrowner_max */
        case 4198344184:
        {
            *enum_result = HAPI_ATTROWNER_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


ERL_NIF_TERM
hapi_get_hapi_attributeowner_c_to_erl(ErlNifEnv* env, HAPI_AttributeOwner enum_value)
{
    switch(enum_value)
    {
        case HAPI_ATTROWNER_INVALID:
        {
            return hapi_make_atom(env, "hapi_attrowner_invalid");
        }

        case HAPI_ATTROWNER_VERTEX:
        {
            return hapi_make_atom(env, "hapi_attrowner_vertex");
        }

        case HAPI_ATTROWNER_POINT:
        {
            return hapi_make_atom(env, "hapi_attrowner_point");
        }

        case HAPI_ATTROWNER_PRIM:
        {
            return hapi_make_atom(env, "hapi_attrowner_prim");
        }

        case HAPI_ATTROWNER_DETAIL:
        {
            return hapi_make_atom(env, "hapi_attrowner_detail");
        }

        case HAPI_ATTROWNER_MAX:
        {
            return hapi_make_atom(env, "hapi_attrowner_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}
