/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_GeoType enum from HAPI_Common.h

#include "../hapi_private_nif.h"
#include <string.h>


bool
hapi_make_hapi_geo_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_GeoType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_geotype_invalid */
        case 2078624117:
        {
            *enum_result = HAPI_GEOTYPE_INVALID;
            break;
        }

        /* hapi_geotype_default */
        case 1702122176:
        {
            *enum_result = HAPI_GEOTYPE_DEFAULT;
            break;
        }

        /* hapi_geotype_intermediate */
        case 2057813327:
        {
            *enum_result = HAPI_GEOTYPE_INTERMEDIATE;
            break;
        }

        /* hapi_geotype_input */
        case 3505553948:
        {
            *enum_result = HAPI_GEOTYPE_INPUT;
            break;
        }

        /* hapi_geotype_curve */
        case 3589938837:
        {
            *enum_result = HAPI_GEOTYPE_CURVE;
            break;
        }

        /* hapi_geotype_max */
        case 2561471983:
        {
            *enum_result = HAPI_GEOTYPE_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


ERL_NIF_TERM
hapi_get_hapi_geo_type(ErlNifEnv* env, HAPI_GeoType enum_value)
{
    switch(enum_value)
    {
        case HAPI_GEOTYPE_INVALID:
        {
            return hapi_make_atom(env, "hapi_geotype_invalid");
        }

        case HAPI_GEOTYPE_DEFAULT:
        {
            return hapi_make_atom(env, "hapi_geotype_default");
        }

        case HAPI_GEOTYPE_INTERMEDIATE:
        {
            return hapi_make_atom(env, "hapi_geotype_intermediate");
        }

        case HAPI_GEOTYPE_INPUT:
        {
            return hapi_make_atom(env, "hapi_geotype_input");
        }

        case HAPI_GEOTYPE_CURVE:
        {
            return hapi_make_atom(env, "hapi_geotype_curve");
        }

        case HAPI_GEOTYPE_MAX:
        {
            return hapi_make_atom(env, "hapi_geotype_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}
