/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_State enum from HAPI_Common.h

#include "../hapi_private_nif.h"
#include <string.h>


bool
hapi_make_hapi_state_(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_State* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_state_ready */
        case 3648387321:
        {
            *enum_result = HAPI_STATE_READY;
            break;
        }

        /* hapi_state_ready_with_fatal_errors */
        case 2824922871:
        {
            *enum_result = HAPI_STATE_READY_WITH_FATAL_ERRORS;
            break;
        }

        /* hapi_state_ready_with_cook_errors */
        case 2342148041:
        {
            *enum_result = HAPI_STATE_READY_WITH_COOK_ERRORS;
            break;
        }

        /* hapi_state_starting_cook */
        case 2553053177:
        {
            *enum_result = HAPI_STATE_STARTING_COOK;
            break;
        }

        /* hapi_state_cooking */
        case 3690862542:
        {
            *enum_result = HAPI_STATE_COOKING;
            break;
        }

        /* hapi_state_starting_load */
        case 3620837358:
        {
            *enum_result = HAPI_STATE_STARTING_LOAD;
            break;
        }

        /* hapi_state_loading */
        case 849338667:
        {
            *enum_result = HAPI_STATE_LOADING;
            break;
        }

        /* hapi_state_max */
        case 3467810446:
        {
            *enum_result = HAPI_STATE_MAX;
            break;
        }

        /* hapi_state_max_ready_state */
        case 35607980:
        {
            *enum_result = HAPI_STATE_MAX_READY_STATE;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


ERL_NIF_TERM
hapi_get_hapi_state_c_to_erl(ErlNifEnv* env, HAPI_State enum_value)
{
    switch(enum_value)
    {
        case HAPI_STATE_READY:
        {
            return hapi_make_atom(env, "hapi_state_ready");
        }

        case HAPI_STATE_READY_WITH_FATAL_ERRORS:
        {
            return hapi_make_atom(env, "hapi_state_ready_with_fatal_errors");
        }

        case HAPI_STATE_READY_WITH_COOK_ERRORS:
        {
            return hapi_make_atom(env, "hapi_state_ready_with_cook_errors");
        }

        case HAPI_STATE_STARTING_COOK:
        {
            return hapi_make_atom(env, "hapi_state_starting_cook");
        }

        case HAPI_STATE_COOKING:
        {
            return hapi_make_atom(env, "hapi_state_cooking");
        }

        case HAPI_STATE_STARTING_LOAD:
        {
            return hapi_make_atom(env, "hapi_state_starting_load");
        }

        case HAPI_STATE_LOADING:
        {
            return hapi_make_atom(env, "hapi_state_loading");
        }

        case HAPI_STATE_MAX:
        {
            return hapi_make_atom(env, "hapi_state_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}
