/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_ParmType enum from HAPI_Common.h

#include "../hapi_private_nif.h"
#include <string.h>


bool
hapi_make_hapi_parmtype(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_ParmType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_parmtype_int */
        case 2938205493:
        {
            *enum_result = HAPI_PARMTYPE_INT;
            break;
        }

        /* hapi_parmtype_multiparmlist */
        case 94525824:
        {
            *enum_result = HAPI_PARMTYPE_MULTIPARMLIST;
            break;
        }

        /* hapi_parmtype_toggle */
        case 3487126731:
        {
            *enum_result = HAPI_PARMTYPE_TOGGLE;
            break;
        }

        /* hapi_parmtype_button */
        case 3222095719:
        {
            *enum_result = HAPI_PARMTYPE_BUTTON;
            break;
        }

        /* hapi_parmtype_float */
        case 3403782401:
        {
            *enum_result = HAPI_PARMTYPE_FLOAT;
            break;
        }

        /* hapi_parmtype_color */
        case 3651575535:
        {
            *enum_result = HAPI_PARMTYPE_COLOR;
            break;
        }

        /* hapi_parmtype_string */
        case 3029524656:
        {
            *enum_result = HAPI_PARMTYPE_STRING;
            break;
        }

        /* hapi_parmtype_path_file */
        case 3946815810:
        {
            *enum_result = HAPI_PARMTYPE_PATH_FILE;
            break;
        }

        /* hapi_parmtype_path_file_geo */
        case 2237470241:
        {
            *enum_result = HAPI_PARMTYPE_PATH_FILE_GEO;
            break;
        }

        /* hapi_parmtype_path_file_image */
        case 3582069620:
        {
            *enum_result = HAPI_PARMTYPE_PATH_FILE_IMAGE;
            break;
        }

        /* hapi_parmtype_path_node */
        case 1563877995:
        {
            *enum_result = HAPI_PARMTYPE_PATH_NODE;
            break;
        }

        /* hapi_parmtype_folderlist */
        case 465413589:
        {
            *enum_result = HAPI_PARMTYPE_FOLDERLIST;
            break;
        }

        /* hapi_parmtype_folder */
        case 1692078012:
        {
            *enum_result = HAPI_PARMTYPE_FOLDER;
            break;
        }

        /* hapi_parmtype_label */
        case 4255272841:
        {
            *enum_result = HAPI_PARMTYPE_LABEL;
            break;
        }

        /* hapi_parmtype_separator */
        case 2360826373:
        {
            *enum_result = HAPI_PARMTYPE_SEPARATOR;
            break;
        }

        /* hapi_parmtype_max */
        case 220098758:
        {
            *enum_result = HAPI_PARMTYPE_MAX;
            break;
        }

        /* hapi_parmtype_int_start */
        case 2793337556:
        {
            *enum_result = HAPI_PARMTYPE_INT_START;
            break;
        }

        /* hapi_parmtype_int_end */
        case 2924084007:
        {
            *enum_result = HAPI_PARMTYPE_INT_END;
            break;
        }

        /* hapi_parmtype_float_start */
        case 3597937322:
        {
            *enum_result = HAPI_PARMTYPE_FLOAT_START;
            break;
        }

        /* hapi_parmtype_float_end */
        case 2584819633:
        {
            *enum_result = HAPI_PARMTYPE_FLOAT_END;
            break;
        }

        /* hapi_parmtype_string_start */
        case 2299523298:
        {
            *enum_result = HAPI_PARMTYPE_STRING_START;
            break;
        }

        /* hapi_parmtype_string_end */
        case 883769106:
        {
            *enum_result = HAPI_PARMTYPE_STRING_END;
            break;
        }

        /* hapi_parmtype_path_start */
        case 1937567703:
        {
            *enum_result = HAPI_PARMTYPE_PATH_START;
            break;
        }

        /* hapi_parmtype_path_end */
        case 233945276:
        {
            *enum_result = HAPI_PARMTYPE_PATH_END;
            break;
        }

        /* hapi_parmtype_path_file_start */
        case 2795114217:
        {
            *enum_result = HAPI_PARMTYPE_PATH_FILE_START;
            break;
        }

        /* hapi_parmtype_path_file_end */
        case 4055995372:
        {
            *enum_result = HAPI_PARMTYPE_PATH_FILE_END;
            break;
        }

        /* hapi_parmtype_path_node_start */
        case 3219598411:
        {
            *enum_result = HAPI_PARMTYPE_PATH_NODE_START;
            break;
        }

        /* hapi_parmtype_path_node_end */
        case 381338848:
        {
            *enum_result = HAPI_PARMTYPE_PATH_NODE_END;
            break;
        }

        /* hapi_parmtype_container_start */
        case 1309661876:
        {
            *enum_result = HAPI_PARMTYPE_CONTAINER_START;
            break;
        }

        /* hapi_parmtype_container_end */
        case 2873311351:
        {
            *enum_result = HAPI_PARMTYPE_CONTAINER_END;
            break;
        }

        /* hapi_parmtype_nonvalue_start */
        case 1808937396:
        {
            *enum_result = HAPI_PARMTYPE_NONVALUE_START;
            break;
        }

        /* hapi_parmtype_nonvalue_end */
        case 920931063:
        {
            *enum_result = HAPI_PARMTYPE_NONVALUE_END;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


ERL_NIF_TERM
hapi_get_hapi_parmtype(ErlNifEnv* env, HAPI_ParmType enum_value)
{
    switch(enum_value)
    {
        case HAPI_PARMTYPE_INT:
        {
            return hapi_make_atom(env, "hapi_parmtype_int");
        }

        case HAPI_PARMTYPE_MULTIPARMLIST:
        {
            return hapi_make_atom(env, "hapi_parmtype_multiparmlist");
        }

        case HAPI_PARMTYPE_TOGGLE:
        {
            return hapi_make_atom(env, "hapi_parmtype_toggle");
        }

        case HAPI_PARMTYPE_BUTTON:
        {
            return hapi_make_atom(env, "hapi_parmtype_button");
        }

        case HAPI_PARMTYPE_FLOAT:
        {
            return hapi_make_atom(env, "hapi_parmtype_float");
        }

        case HAPI_PARMTYPE_COLOR:
        {
            return hapi_make_atom(env, "hapi_parmtype_color");
        }

        case HAPI_PARMTYPE_STRING:
        {
            return hapi_make_atom(env, "hapi_parmtype_string");
        }

        case HAPI_PARMTYPE_PATH_FILE:
        {
            return hapi_make_atom(env, "hapi_parmtype_path_file");
        }

        case HAPI_PARMTYPE_PATH_FILE_GEO:
        {
            return hapi_make_atom(env, "hapi_parmtype_path_file_geo");
        }

        case HAPI_PARMTYPE_PATH_FILE_IMAGE:
        {
            return hapi_make_atom(env, "hapi_parmtype_path_file_image");
        }

        case HAPI_PARMTYPE_PATH_NODE:
        {
            return hapi_make_atom(env, "hapi_parmtype_path_node");
        }

        case HAPI_PARMTYPE_FOLDERLIST:
        {
            return hapi_make_atom(env, "hapi_parmtype_folderlist");
        }

        case HAPI_PARMTYPE_FOLDER:
        {
            return hapi_make_atom(env, "hapi_parmtype_folder");
        }

        case HAPI_PARMTYPE_LABEL:
        {
            return hapi_make_atom(env, "hapi_parmtype_label");
        }

        case HAPI_PARMTYPE_SEPARATOR:
        {
            return hapi_make_atom(env, "hapi_parmtype_separator");
        }

        case HAPI_PARMTYPE_MAX:
        {
            return hapi_make_atom(env, "hapi_parmtype_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}
