/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_GroupType enum from HAPI_Common.h

#include "../hapi_private_nif.h"
#include <string.h>


bool
hapi_make_hapi_group_type(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_GroupType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0u;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_grouptype_invalid */
        case 1807777027:
        {
            *enum_result = HAPI_GROUPTYPE_INVALID;
            break;
        }

        /* hapi_grouptype_point */
        case 3354691949:
        {
            *enum_result = HAPI_GROUPTYPE_POINT;
            break;
        }

        /* hapi_grouptype_prim */
        case 2860112191:
        {
            *enum_result = HAPI_GROUPTYPE_PRIM;
            break;
        }

        /* hapi_grouptype_max */
        case 2983497873:
        {
            *enum_result = HAPI_GROUPTYPE_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


ERL_NIF_TERM
hapi_get_hapi_group_type(ErlNifEnv* env, HAPI_GroupType enum_value)
{
    switch(enum_value)
    {
        case HAPI_GROUPTYPE_INVALID:
        {
            return hapi_make_atom(env, "hapi_grouptype_invalid");
        }

        case HAPI_GROUPTYPE_POINT:
        {
            return hapi_make_atom(env, "hapi_grouptype_point");
        }

        case HAPI_GROUPTYPE_PRIM:
        {
            return hapi_make_atom(env, "hapi_grouptype_prim");
        }

        case HAPI_GROUPTYPE_MAX:
        {
            return hapi_make_atom(env, "hapi_grouptype_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}
