/// @author Mykola Konyk <mykola@konyk.org>
///
/// @copyright 2015
/// @license MS-RL
/// This file is autogenerated from util/hapi_enum_nif.c.template
/// This file corresponds to HAPI_PresetType enum from HAPI_Common.h

#include "../hapi_private_nif.h"
#include <string.h>


bool
hapi_presettype_erl_to_c(ErlNifEnv* env, const ERL_NIF_TERM term, HAPI_PresetType* enum_result)
{
    bool nif_success = true;
    uint32_t atom_len = 0;
    uint32_t atom_hash = 0u;
    char* atom_value = NULL;

    if(!enif_get_atom_length(env, term, &atom_len, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_value = malloc(atom_len + 1);
    memset(atom_value, 0, atom_len + 1);

    if(!enif_get_atom(env, term, atom_value, atom_len + 1, ERL_NIF_LATIN1))
    {
        nif_success = false;
        goto label_cleanup;
    }

    atom_hash = XXH32(atom_value, strlen(atom_value), 0);

    switch(atom_hash)
    {
        /* hapi_presettype_invalid */
        case 3370572381:
        {
            *enum_result = HAPI_PRESETTYPE_INVALID;
            break;
        }

        /* hapi_presettype_binary */
        case 1629204808:
        {
            *enum_result = HAPI_PRESETTYPE_BINARY;
            break;
        }

        /* hapi_presettype_idx */
        case 2476503831:
        {
            *enum_result = HAPI_PRESETTYPE_IDX;
            break;
        }

        /* hapi_presettype_max */
        case 1183497328:
        {
            *enum_result = HAPI_PRESETTYPE_MAX;
            break;
        }

        default:
        {
            nif_success = false;
            break;
        }
    }

label_cleanup:

    if(atom_value)
    {
        free(atom_value);
    }

    return nif_success;
}


ERL_NIF_TERM
hapi_presettype_c_to_erl(ErlNifEnv* env, HAPI_PresetType enum_value)
{
    switch(enum_value)
    {
        case HAPI_PRESETTYPE_INVALID:
        {
            return hapi_make_atom(env, "hapi_presettype_invalid");
        }

        case HAPI_PRESETTYPE_BINARY:
        {
            return hapi_make_atom(env, "hapi_presettype_binary");
        }

        case HAPI_PRESETTYPE_IDX:
        {
            return hapi_make_atom(env, "hapi_presettype_idx");
        }

        case HAPI_PRESETTYPE_MAX:
        {
            return hapi_make_atom(env, "hapi_presettype_max");
        }

        default:
        {
            break;
        }
    }

    return enif_make_badarg(env);
}
