%%% @author Mykola Konyk  <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from HAPI_Common.h from HAPI_Keyframe structure.

-record(hapi_keyframe,
{
    time,
    value,
    in_tangent,
    out_tangent
}).
