%%% @author Mykola Konyk <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% @license MS-RL
%%% This file is autogenerated from hapi_record.hrl.template
%%% This file corresponds to HAPI_AttributeInfo structure from HAPI_Common.h

-record(hapi_attribute_info,
{
    exists,
    owner,
    storage,
    original_owner,
    count,
    tuple_size
}).
