%%% @author Mykola Konyk <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from hapi_record.hrl.template
%%% This file corresponds to HAPI_HandleBindingInfo structure from HAPI_Common.h

-record(hapi_handle_binding_info,
{
    handle_parm_name_sh,
    asset_parm_name_sh,
    asset_parm_id
}).
