%%% @author Mykola Konyk <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% @license MS-RL
%%% This file is autogenerated from util/hapi_records.hrl.template

-include("records/hapi_cookoptions.hrl").
-include("records/hapi_keyframe.hrl").
-include("records/hapi_partinfo.hrl").
-include("records/hapi_materialinfo.hrl").
-include("records/hapi_globalnodes.hrl").
-include("records/hapi_handlebindinginfo.hrl").
-include("records/hapi_imageinfo.hrl").
-include("records/hapi_volumeinfo.hrl").
-include("records/hapi_geoinputinfo.hrl").
-include("records/hapi_volumetileinfo.hrl").
-include("records/hapi_curveinfo.hrl").
-include("records/hapi_transform.hrl").
-include("records/hapi_imagefileformat.hrl").
-include("records/hapi_transformeuler.hrl").
-include("records/hapi_attributeinfo.hrl").
-include("records/hapi_geoinfo.hrl").
-include("records/hapi_assetinfo.hrl").
-include("records/hapi_parmchoiceinfo.hrl").
-include("records/hapi_objectinfo.hrl").
-include("records/hapi_handleinfo.hrl").
-include("records/hapi_timelineoptions.hrl").
-include("records/hapi_nodeinfo.hrl").
-include("records/hapi_parminfo.hrl").
