%%% @author Mykola Konyk  <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from HAPI_Common.h from HAPI_CookOptions structure.

-record(hapi_cook_options,
{
    split_geos_by_group,
    max_vertices_per_primitive,
    refine_curve_to_linear,
    curve_refine_lod,
    clear_errors_and_warnings,
    cook_templated_geos
}).
