%%% @author Mykola Konyk <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from hapi_records.hrl.template

-include("hapi_record_transform.hrl").
-include("hapi_record_transform_euler.hrl").
-include("hapi_record_timeline_options.hrl").
-include("hapi_record_asset_info.hrl").
-include("hapi_record_cook_options.hrl").
-include("hapi_record_node_info.hrl").
-include("hapi_record_global_nodes.hrl").
-include("hapi_record_parm_info.hrl").
-include("hapi_record_parm_choice_info.hrl").
-include("hapi_record_handle_info.hrl").
-include("hapi_record_handle_binding_info.hrl").
-include("hapi_record_object_info.hrl").
-include("hapi_record_geo_info.hrl").
-include("hapi_record_geo_input_info.hrl").
-include("hapi_record_part_info.hrl").
-include("hapi_record_attribute_info.hrl").
-include("hapi_record_material_info.hrl").
-include("hapi_record_image_file_format.hrl").
-include("hapi_record_image_info.hrl").
-include("hapi_record_keyframe.hrl").
-include("hapi_record_volume_info.hrl").
-include("hapi_record_volume_tile_info.hrl").
-include("hapi_record_curve_info.hrl").
