%%% @author Mykola Konyk  <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from HAPI_Common.h from HAPI_HandleBindingInfo structure.

-record(hapi_handle_binding_info,
{
    handle_parm_name_sh,
    asset_parm_name_sh,
    asset_parm_id
}).
