%%% @author Mykola Konyk <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% @license MS-RL
%%% This file is autogenerated from hapi_record.hrl.template
%%% This file corresponds to HAPI_MaterialInfo structure from HAPI_Common.h

-record(hapi_material_info,
{
    id,
    asset_id,
    node_id,
    exists,
    has_changed
}).
