%%% @author Mykola Konyk <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from hapi_record.hrl.template
%%% This file corresponds to HAPI_NodeInfo structure from HAPI_Common.h

-record(hapi_node_info,
{
    id,
    asset_id,
    name_sh,
    total_cook_count,
    unique_houdini_node_id,
    internal_node_path_sh,
    parm_count,
    parm_int_value_count,
    parm_float_value_count,
    parm_string_value_count,
    parm_choice_count
}).
