%%% @author Mykola Konyk  <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from HAPI_Common.h from HAPI_ImageInfo structure.

-record(hapi_image_info,
{
    image_file_format_name_sh,
    x_res,
    y_res,
    data_format,
    interleaved,
    packing,
    gamma
}).
