%%% @author Mykola Konyk  <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from HAPI_Common.h from HAPI_GeoInfo structure.

-record(hapi_geo_info,
{
    id,
    type,
    name_sh,
    node_id,
    is_editable,
    is_templated,
    is_display_geo,
    has_geo_changed,
    has_material_changed,
    point_group_count,
    primitive_group_count,
    part_count
}).
