%%% @author Mykola Konyk  <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from HAPI_Common.h from HAPI_AttributeInfo structure.

-record(hapi_attribute_info,
{
    exists,
    owner,
    storage,
    original_owner,
    count,
    tuple_size
}).
