%%% @author Mykola Konyk  <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from HAPI_Common.h from HAPI_Transform structure.

-record(hapi_transform,
{
    position,
    rotation_quaternion,
    scale,
    rst_order
}).
