%%% @author Mykola Konyk <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from hapi_record.hrl.template
%%% This file corresponds to HAPI_GlobalNodes structure from HAPI_Common.h

-record(hapi_global_nodes,
{
    default_camera,
    default_light,
    mantra_renderer
}).
