%%% @author Mykola Konyk  <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from hapi_record.hrl.template
%%% This file corresponds to HAPI_AssetInfo structure from HAPI_Common.h

-record(hapi_asset_info,
{
    id,
    type,
    sub_type,
    validation_id,
    node_id,
    object_node_id,
    has_ever_cooked,
    name_sh,
    label_sh,
    file_path_sh,
    version_sh,
    full_op_name_sh,
    help_text_sh,
    object_count,
    handle_count,
    transform_input_count,
    geo_input_count,
    have_objects_changed,
    have_materials_changed
}).
