%%% @author Mykola Konyk  <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from HAPI_Common.h from HAPI_GlobalNodes structure.

-record(hapi_global_nodes,
{
    default_camera,
    default_light,
    mantra_renderer
}).
