%%% @author Mykola Konyk  <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from HAPI_Common.h from HAPI_CurveInfo structure.

-record(hapi_curve_info,
{
    curve_type,
    curve_count,
    vertex_count,
    knot_count,
    is_periodic,
    is_rational,
    order,
    has_knots
}).
