%%% @author Mykola Konyk  <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from HAPI_Common.h from HAPI_TimelineOptions structure.

-record(hapi_timeline_options,
{
    fps,
    start_time,
    end_time
}).
