%%% @author Mykola Konyk  <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from HAPI_Common.h from HAPI_HandleInfo structure.

-record(hapi_handle_info,
{
    name_sh,
    type_name_sh,
    bindings_count
}).
