%%% @author Mykola Konyk  <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from hapi_record.hrl.template
%%% This file corresponds to HAPI_ParmChoiceInfo structure from HAPI_Common.h

-record(hapi_parm_choice_info,
{
    parent_parm_id,
    label_sh,
    value_sh
}).
