%%% @author Mykola Konyk  <mykola@konyk.org>
%%%
%%% @copyright 2015
%%% This file is autogenerated from HAPI_Common.h from HAPI_VolumeTileInfo structure.

-record(hapi_volume_tile_info,
{
    min_x,
    min_y,
    min_z,
    is_valid
}).
